apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        orgId: 1
        url: http://cerberus-tempo:3200
        basicAuth: false
        isDefault: false
        version: 1
        editable: false
        apiVersion: 1
        uid: tempo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-dashboards
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'dashboards'
        orgId: 1
        type: file
        disableDeletion: true
        editable: true
        updateIntervalSeconds: 10
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true
