// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user_roles_permissions_test

import (
	"context"

	"github.com/Housiadas/cerberus/db/sqlc"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// newMockstorer creates a new instance of mockstorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstorer {
	mock := &mockstorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstorer is an autogenerated mock type for the storer type
type mockstorer struct {
	mock.Mock
}

type mockstorer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstorer) EXPECT() *mockstorer_Expecter {
	return &mockstorer_Expecter{mock: &_m.Mock}
}

// GetPermissionsByUserID provides a mock function for the type mockstorer
func (_mock *mockstorer) GetPermissionsByUserID(ctx context.Context, userID uuid.UUID) ([]db.GetPermissionsByUserIDRow, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionsByUserID")
	}

	var r0 []db.GetPermissionsByUserIDRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]db.GetPermissionsByUserIDRow, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []db.GetPermissionsByUserIDRow); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetPermissionsByUserIDRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstorer_GetPermissionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionsByUserID'
type mockstorer_GetPermissionsByUserID_Call struct {
	*mock.Call
}

// GetPermissionsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *mockstorer_Expecter) GetPermissionsByUserID(ctx interface{}, userID interface{}) *mockstorer_GetPermissionsByUserID_Call {
	return &mockstorer_GetPermissionsByUserID_Call{Call: _e.mock.On("GetPermissionsByUserID", ctx, userID)}
}

func (_c *mockstorer_GetPermissionsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *mockstorer_GetPermissionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_GetPermissionsByUserID_Call) Return(getPermissionsByUserIDRows []db.GetPermissionsByUserIDRow, err error) *mockstorer_GetPermissionsByUserID_Call {
	_c.Call.Return(getPermissionsByUserIDRows, err)
	return _c
}

func (_c *mockstorer_GetPermissionsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]db.GetPermissionsByUserIDRow, error)) *mockstorer_GetPermissionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}
