// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user_roles_permissions_test

import (
	"context"

	"github.com/Housiadas/cerberus/internal/core/user_roles_permissions"
	"github.com/Housiadas/cerberus/pkg/cursor"
	"github.com/Housiadas/cerberus/pkg/order"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// HasPermission provides a mock function for the type MockStorer
func (_mock *MockStorer) HasPermission(ctx context.Context, userID uuid.UUID, permissionName string) (bool, error) {
	ret := _mock.Called(ctx, userID, permissionName)

	if len(ret) == 0 {
		panic("no return value specified for HasPermission")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return returnFunc(ctx, userID, permissionName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = returnFunc(ctx, userID, permissionName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, permissionName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_HasPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPermission'
type MockStorer_HasPermission_Call struct {
	*mock.Call
}

// HasPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - permissionName string
func (_e *MockStorer_Expecter) HasPermission(ctx interface{}, userID interface{}, permissionName interface{}) *MockStorer_HasPermission_Call {
	return &MockStorer_HasPermission_Call{Call: _e.mock.On("HasPermission", ctx, userID, permissionName)}
}

func (_c *MockStorer_HasPermission_Call) Run(run func(ctx context.Context, userID uuid.UUID, permissionName string)) *MockStorer_HasPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorer_HasPermission_Call) Return(b bool, err error) *MockStorer_HasPermission_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStorer_HasPermission_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, permissionName string) (bool, error)) *MockStorer_HasPermission_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockStorer
func (_mock *MockStorer) Query(ctx context.Context, filter user_roles_permissions.QueryFilter, orderBy order.By, cur cursor.Cursor) ([]user_roles_permissions.UserRolesPermissions, error) {
	ret := _mock.Called(ctx, filter, orderBy, cur)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []user_roles_permissions.UserRolesPermissions
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user_roles_permissions.QueryFilter, order.By, cursor.Cursor) ([]user_roles_permissions.UserRolesPermissions, error)); ok {
		return returnFunc(ctx, filter, orderBy, cur)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user_roles_permissions.QueryFilter, order.By, cursor.Cursor) []user_roles_permissions.UserRolesPermissions); ok {
		r0 = returnFunc(ctx, filter, orderBy, cur)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user_roles_permissions.UserRolesPermissions)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user_roles_permissions.QueryFilter, order.By, cursor.Cursor) error); ok {
		r1 = returnFunc(ctx, filter, orderBy, cur)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockStorer_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - filter user_roles_permissions.QueryFilter
//   - orderBy order.By
//   - cur cursor.Cursor
func (_e *MockStorer_Expecter) Query(ctx interface{}, filter interface{}, orderBy interface{}, cur interface{}) *MockStorer_Query_Call {
	return &MockStorer_Query_Call{Call: _e.mock.On("Query", ctx, filter, orderBy, cur)}
}

func (_c *MockStorer_Query_Call) Run(run func(ctx context.Context, filter user_roles_permissions.QueryFilter, orderBy order.By, cur cursor.Cursor)) *MockStorer_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user_roles_permissions.QueryFilter
		if args[1] != nil {
			arg1 = args[1].(user_roles_permissions.QueryFilter)
		}
		var arg2 order.By
		if args[2] != nil {
			arg2 = args[2].(order.By)
		}
		var arg3 cursor.Cursor
		if args[3] != nil {
			arg3 = args[3].(cursor.Cursor)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorer_Query_Call) Return(userRolesPermissionss []user_roles_permissions.UserRolesPermissions, err error) *MockStorer_Query_Call {
	_c.Call.Return(userRolesPermissionss, err)
	return _c
}

func (_c *MockStorer_Query_Call) RunAndReturn(run func(ctx context.Context, filter user_roles_permissions.QueryFilter, orderBy order.By, cur cursor.Cursor) ([]user_roles_permissions.UserRolesPermissions, error)) *MockStorer_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryPermissionsByUserID provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryPermissionsByUserID(ctx context.Context, userID uuid.UUID) ([]user_roles_permissions.Permission, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for QueryPermissionsByUserID")
	}

	var r0 []user_roles_permissions.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]user_roles_permissions.Permission, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []user_roles_permissions.Permission); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user_roles_permissions.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryPermissionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryPermissionsByUserID'
type MockStorer_QueryPermissionsByUserID_Call struct {
	*mock.Call
}

// QueryPermissionsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStorer_Expecter) QueryPermissionsByUserID(ctx interface{}, userID interface{}) *MockStorer_QueryPermissionsByUserID_Call {
	return &MockStorer_QueryPermissionsByUserID_Call{Call: _e.mock.On("QueryPermissionsByUserID", ctx, userID)}
}

func (_c *MockStorer_QueryPermissionsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStorer_QueryPermissionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_QueryPermissionsByUserID_Call) Return(permissions []user_roles_permissions.Permission, err error) *MockStorer_QueryPermissionsByUserID_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *MockStorer_QueryPermissionsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]user_roles_permissions.Permission, error)) *MockStorer_QueryPermissionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// newMocklogger creates a new instance of mocklogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocklogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocklogger {
	mock := &mocklogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocklogger is an autogenerated mock type for the logger type
type mocklogger struct {
	mock.Mock
}

type mocklogger_Expecter struct {
	mock *mock.Mock
}

func (_m *mocklogger) EXPECT() *mocklogger_Expecter {
	return &mocklogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type mocklogger
func (_mock *mocklogger) Debug(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type mocklogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Debug(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Debug_Call {
	return &mocklogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Debug_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Debug_Call) Return() *mocklogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Debug_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Debugc provides a mock function for the type mocklogger
func (_mock *mocklogger) Debugc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Debugc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugc'
type mocklogger_Debugc_Call struct {
	*mock.Call
}

// Debugc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Debugc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Debugc_Call {
	return &mocklogger_Debugc_Call{Call: _e.mock.On("Debugc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Debugc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Debugc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Debugc_Call) Return() *mocklogger_Debugc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Debugc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Debugc_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type mocklogger
func (_mock *mocklogger) Error(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type mocklogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Error(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Error_Call {
	return &mocklogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Error_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Error_Call) Return() *mocklogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Error_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Error_Call {
	_c.Run(run)
	return _c
}

// Errorc provides a mock function for the type mocklogger
func (_mock *mocklogger) Errorc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Errorc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorc'
type mocklogger_Errorc_Call struct {
	*mock.Call
}

// Errorc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Errorc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Errorc_Call {
	return &mocklogger_Errorc_Call{Call: _e.mock.On("Errorc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Errorc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Errorc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Errorc_Call) Return() *mocklogger_Errorc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Errorc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Errorc_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type mocklogger
func (_mock *mocklogger) Info(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type mocklogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Info(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Info_Call {
	return &mocklogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Info_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Info_Call) Return() *mocklogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Info_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Info_Call {
	_c.Run(run)
	return _c
}

// Infoc provides a mock function for the type mocklogger
func (_mock *mocklogger) Infoc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Infoc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infoc'
type mocklogger_Infoc_Call struct {
	*mock.Call
}

// Infoc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Infoc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Infoc_Call {
	return &mocklogger_Infoc_Call{Call: _e.mock.On("Infoc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Infoc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Infoc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Infoc_Call) Return() *mocklogger_Infoc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Infoc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Infoc_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type mocklogger
func (_mock *mocklogger) Warn(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type mocklogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Warn(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Warn_Call {
	return &mocklogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Warn_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Warn_Call) Return() *mocklogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Warn_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Warn_Call {
	_c.Run(run)
	return _c
}

// Warnc provides a mock function for the type mocklogger
func (_mock *mocklogger) Warnc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Warnc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warnc'
type mocklogger_Warnc_Call struct {
	*mock.Call
}

// Warnc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Warnc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Warnc_Call {
	return &mocklogger_Warnc_Call{Call: _e.mock.On("Warnc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Warnc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Warnc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Warnc_Call) Return() *mocklogger_Warnc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Warnc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Warnc_Call {
	_c.Run(run)
	return _c
}
