// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package account_test

import (
	"context"
	"time"

	"github.com/Housiadas/cerberus/db/sqlc"
	"github.com/Housiadas/cerberus/pkg/cursor"
	"github.com/Housiadas/cerberus/pkg/order"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// newMockgenerator creates a new instance of mockgenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockgenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockgenerator {
	mock := &mockgenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockgenerator is an autogenerated mock type for the generator type
type mockgenerator struct {
	mock.Mock
}

type mockgenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockgenerator) EXPECT() *mockgenerator_Expecter {
	return &mockgenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type mockgenerator
func (_mock *mockgenerator) Generate() (uuid.UUID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uuid.UUID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockgenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type mockgenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *mockgenerator_Expecter) Generate() *mockgenerator_Generate_Call {
	return &mockgenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *mockgenerator_Generate_Call) Run(run func()) *mockgenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockgenerator_Generate_Call) Return(uUID uuid.UUID, err error) *mockgenerator_Generate_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *mockgenerator_Generate_Call) RunAndReturn(run func() (uuid.UUID, error)) *mockgenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockclock creates a new instance of mockclock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockclock(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockclock {
	mock := &mockclock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockclock is an autogenerated mock type for the clock type
type mockclock struct {
	mock.Mock
}

type mockclock_Expecter struct {
	mock *mock.Mock
}

func (_m *mockclock) EXPECT() *mockclock_Expecter {
	return &mockclock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type mockclock
func (_mock *mockclock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// mockclock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type mockclock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *mockclock_Expecter) Now() *mockclock_Now_Call {
	return &mockclock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *mockclock_Now_Call) Run(run func()) *mockclock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockclock_Now_Call) Return(time1 time.Time) *mockclock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *mockclock_Now_Call) RunAndReturn(run func() time.Time) *mockclock_Now_Call {
	_c.Call.Return(run)
	return _c
}

// newMocktransactor creates a new instance of mocktransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktransactor {
	mock := &mocktransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocktransactor is an autogenerated mock type for the transactor type
type mocktransactor struct {
	mock.Mock
}

type mocktransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktransactor) EXPECT() *mocktransactor_Expecter {
	return &mocktransactor_Expecter{mock: &_m.Mock}
}

// RunInTx provides a mock function for the type mocktransactor
func (_mock *mocktransactor) RunInTx(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunInTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocktransactor_RunInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInTx'
type mocktransactor_RunInTx_Call struct {
	*mock.Call
}

// RunInTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *mocktransactor_Expecter) RunInTx(ctx interface{}, fn interface{}) *mocktransactor_RunInTx_Call {
	return &mocktransactor_RunInTx_Call{Call: _e.mock.On("RunInTx", ctx, fn)}
}

func (_c *mocktransactor_RunInTx_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *mocktransactor_RunInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocktransactor_RunInTx_Call) Return(err error) *mocktransactor_RunInTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocktransactor_RunInTx_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *mocktransactor_RunInTx_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstorer creates a new instance of mockstorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstorer {
	mock := &mockstorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstorer is an autogenerated mock type for the storer type
type mockstorer struct {
	mock.Mock
}

type mockstorer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstorer) EXPECT() *mockstorer_Expecter {
	return &mockstorer_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function for the type mockstorer
func (_mock *mockstorer) CreateAccount(ctx context.Context, arg db.CreateAccountParams) (db.Account, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 db.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateAccountParams) (db.Account, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateAccountParams) db.Account); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Account)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateAccountParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstorer_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type mockstorer_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateAccountParams
func (_e *mockstorer_Expecter) CreateAccount(ctx interface{}, arg interface{}) *mockstorer_CreateAccount_Call {
	return &mockstorer_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, arg)}
}

func (_c *mockstorer_CreateAccount_Call) Run(run func(ctx context.Context, arg db.CreateAccountParams)) *mockstorer_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateAccountParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateAccountParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_CreateAccount_Call) Return(account db.Account, err error) *mockstorer_CreateAccount_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *mockstorer_CreateAccount_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateAccountParams) (db.Account, error)) *mockstorer_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function for the type mockstorer
func (_mock *mockstorer) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstorer_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type mockstorer_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *mockstorer_Expecter) DeleteAccount(ctx interface{}, id interface{}) *mockstorer_DeleteAccount_Call {
	return &mockstorer_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, id)}
}

func (_c *mockstorer_DeleteAccount_Call) Run(run func(ctx context.Context, id uuid.UUID)) *mockstorer_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_DeleteAccount_Call) Return(err error) *mockstorer_DeleteAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstorer_DeleteAccount_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *mockstorer_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByID provides a mock function for the type mockstorer
func (_mock *mockstorer) GetAccountByID(ctx context.Context, id uuid.UUID) (db.GetAccountByIDRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByID")
	}

	var r0 db.GetAccountByIDRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.GetAccountByIDRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.GetAccountByIDRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.GetAccountByIDRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstorer_GetAccountByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByID'
type mockstorer_GetAccountByID_Call struct {
	*mock.Call
}

// GetAccountByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *mockstorer_Expecter) GetAccountByID(ctx interface{}, id interface{}) *mockstorer_GetAccountByID_Call {
	return &mockstorer_GetAccountByID_Call{Call: _e.mock.On("GetAccountByID", ctx, id)}
}

func (_c *mockstorer_GetAccountByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *mockstorer_GetAccountByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_GetAccountByID_Call) Return(getAccountByIDRow db.GetAccountByIDRow, err error) *mockstorer_GetAccountByID_Call {
	_c.Call.Return(getAccountByIDRow, err)
	return _c
}

func (_c *mockstorer_GetAccountByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (db.GetAccountByIDRow, error)) *mockstorer_GetAccountByID_Call {
	_c.Call.Return(run)
	return _c
}

// QueryAccounts provides a mock function for the type mockstorer
func (_mock *mockstorer) QueryAccounts(ctx context.Context, filter db.AccountQueryFilter, orderBy order.By, cur cursor.Cursor) ([]db.Account, error) {
	ret := _mock.Called(ctx, filter, orderBy, cur)

	if len(ret) == 0 {
		panic("no return value specified for QueryAccounts")
	}

	var r0 []db.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.AccountQueryFilter, order.By, cursor.Cursor) ([]db.Account, error)); ok {
		return returnFunc(ctx, filter, orderBy, cur)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.AccountQueryFilter, order.By, cursor.Cursor) []db.Account); ok {
		r0 = returnFunc(ctx, filter, orderBy, cur)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.AccountQueryFilter, order.By, cursor.Cursor) error); ok {
		r1 = returnFunc(ctx, filter, orderBy, cur)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstorer_QueryAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryAccounts'
type mockstorer_QueryAccounts_Call struct {
	*mock.Call
}

// QueryAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter db.AccountQueryFilter
//   - orderBy order.By
//   - cur cursor.Cursor
func (_e *mockstorer_Expecter) QueryAccounts(ctx interface{}, filter interface{}, orderBy interface{}, cur interface{}) *mockstorer_QueryAccounts_Call {
	return &mockstorer_QueryAccounts_Call{Call: _e.mock.On("QueryAccounts", ctx, filter, orderBy, cur)}
}

func (_c *mockstorer_QueryAccounts_Call) Run(run func(ctx context.Context, filter db.AccountQueryFilter, orderBy order.By, cur cursor.Cursor)) *mockstorer_QueryAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.AccountQueryFilter
		if args[1] != nil {
			arg1 = args[1].(db.AccountQueryFilter)
		}
		var arg2 order.By
		if args[2] != nil {
			arg2 = args[2].(order.By)
		}
		var arg3 cursor.Cursor
		if args[3] != nil {
			arg3 = args[3].(cursor.Cursor)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockstorer_QueryAccounts_Call) Return(accounts []db.Account, err error) *mockstorer_QueryAccounts_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *mockstorer_QueryAccounts_Call) RunAndReturn(run func(ctx context.Context, filter db.AccountQueryFilter, orderBy order.By, cur cursor.Cursor) ([]db.Account, error)) *mockstorer_QueryAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccount provides a mock function for the type mockstorer
func (_mock *mockstorer) UpdateAccount(ctx context.Context, arg db.UpdateAccountParams) (db.Account, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 db.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateAccountParams) (db.Account, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateAccountParams) db.Account); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Account)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.UpdateAccountParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstorer_UpdateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccount'
type mockstorer_UpdateAccount_Call struct {
	*mock.Call
}

// UpdateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateAccountParams
func (_e *mockstorer_Expecter) UpdateAccount(ctx interface{}, arg interface{}) *mockstorer_UpdateAccount_Call {
	return &mockstorer_UpdateAccount_Call{Call: _e.mock.On("UpdateAccount", ctx, arg)}
}

func (_c *mockstorer_UpdateAccount_Call) Run(run func(ctx context.Context, arg db.UpdateAccountParams)) *mockstorer_UpdateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.UpdateAccountParams
		if args[1] != nil {
			arg1 = args[1].(db.UpdateAccountParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_UpdateAccount_Call) Return(account db.Account, err error) *mockstorer_UpdateAccount_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *mockstorer_UpdateAccount_Call) RunAndReturn(run func(ctx context.Context, arg db.UpdateAccountParams) (db.Account, error)) *mockstorer_UpdateAccount_Call {
	_c.Call.Return(run)
	return _c
}
