// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package relay_test

import (
	"context"

	"github.com/Housiadas/cerberus/internal/core/outbox"
	"github.com/confluentinc/confluent-kafka-go/v2/kafka"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// newMockproducer creates a new instance of mockproducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockproducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockproducer {
	mock := &mockproducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockproducer is an autogenerated mock type for the producer type
type mockproducer struct {
	mock.Mock
}

type mockproducer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockproducer) EXPECT() *mockproducer_Expecter {
	return &mockproducer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type mockproducer
func (_mock *mockproducer) Close() {
	_mock.Called()
	return
}

// mockproducer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockproducer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *mockproducer_Expecter) Close() *mockproducer_Close_Call {
	return &mockproducer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *mockproducer_Close_Call) Run(run func()) *mockproducer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockproducer_Close_Call) Return() *mockproducer_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockproducer_Close_Call) RunAndReturn(run func()) *mockproducer_Close_Call {
	_c.Run(run)
	return _c
}

// Flush provides a mock function for the type mockproducer
func (_mock *mockproducer) Flush(timeoutMs int) int {
	ret := _mock.Called(timeoutMs)

	if len(ret) == 0 {
		panic("no return value specified for Flush")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(int) int); ok {
		r0 = returnFunc(timeoutMs)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// mockproducer_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type mockproducer_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
//   - timeoutMs int
func (_e *mockproducer_Expecter) Flush(timeoutMs interface{}) *mockproducer_Flush_Call {
	return &mockproducer_Flush_Call{Call: _e.mock.On("Flush", timeoutMs)}
}

func (_c *mockproducer_Flush_Call) Run(run func(timeoutMs int)) *mockproducer_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockproducer_Flush_Call) Return(n int) *mockproducer_Flush_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *mockproducer_Flush_Call) RunAndReturn(run func(timeoutMs int) int) *mockproducer_Flush_Call {
	_c.Call.Return(run)
	return _c
}

// Produce provides a mock function for the type mockproducer
func (_mock *mockproducer) Produce(ctx context.Context, msg *kafka.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockproducer_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type mockproducer_Produce_Call struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *kafka.Message
func (_e *mockproducer_Expecter) Produce(ctx interface{}, msg interface{}) *mockproducer_Produce_Call {
	return &mockproducer_Produce_Call{Call: _e.mock.On("Produce", ctx, msg)}
}

func (_c *mockproducer_Produce_Call) Run(run func(ctx context.Context, msg *kafka.Message)) *mockproducer_Produce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kafka.Message
		if args[1] != nil {
			arg1 = args[1].(*kafka.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockproducer_Produce_Call) Return(err error) *mockproducer_Produce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockproducer_Produce_Call) RunAndReturn(run func(ctx context.Context, msg *kafka.Message) error) *mockproducer_Produce_Call {
	_c.Call.Return(run)
	return _c
}

// newMockoutboxer creates a new instance of mockoutboxer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockoutboxer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockoutboxer {
	mock := &mockoutboxer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockoutboxer is an autogenerated mock type for the outboxer type
type mockoutboxer struct {
	mock.Mock
}

type mockoutboxer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockoutboxer) EXPECT() *mockoutboxer_Expecter {
	return &mockoutboxer_Expecter{mock: &_m.Mock}
}

// IncrementRetryCount provides a mock function for the type mockoutboxer
func (_mock *mockoutboxer) IncrementRetryCount(ctx context.Context, ids []uuid.UUID) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for IncrementRetryCount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockoutboxer_IncrementRetryCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementRetryCount'
type mockoutboxer_IncrementRetryCount_Call struct {
	*mock.Call
}

// IncrementRetryCount is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *mockoutboxer_Expecter) IncrementRetryCount(ctx interface{}, ids interface{}) *mockoutboxer_IncrementRetryCount_Call {
	return &mockoutboxer_IncrementRetryCount_Call{Call: _e.mock.On("IncrementRetryCount", ctx, ids)}
}

func (_c *mockoutboxer_IncrementRetryCount_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *mockoutboxer_IncrementRetryCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockoutboxer_IncrementRetryCount_Call) Return(err error) *mockoutboxer_IncrementRetryCount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockoutboxer_IncrementRetryCount_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) error) *mockoutboxer_IncrementRetryCount_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessed provides a mock function for the type mockoutboxer
func (_mock *mockoutboxer) MarkProcessed(ctx context.Context, ids []uuid.UUID) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockoutboxer_MarkProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessed'
type mockoutboxer_MarkProcessed_Call struct {
	*mock.Call
}

// MarkProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *mockoutboxer_Expecter) MarkProcessed(ctx interface{}, ids interface{}) *mockoutboxer_MarkProcessed_Call {
	return &mockoutboxer_MarkProcessed_Call{Call: _e.mock.On("MarkProcessed", ctx, ids)}
}

func (_c *mockoutboxer_MarkProcessed_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *mockoutboxer_MarkProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockoutboxer_MarkProcessed_Call) Return(err error) *mockoutboxer_MarkProcessed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockoutboxer_MarkProcessed_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) error) *mockoutboxer_MarkProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// QueryUnprocessed provides a mock function for the type mockoutboxer
func (_mock *mockoutboxer) QueryUnprocessed(ctx context.Context, batchSize int, maxRetries int) ([]outbox.Outbox, error) {
	ret := _mock.Called(ctx, batchSize, maxRetries)

	if len(ret) == 0 {
		panic("no return value specified for QueryUnprocessed")
	}

	var r0 []outbox.Outbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]outbox.Outbox, error)); ok {
		return returnFunc(ctx, batchSize, maxRetries)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []outbox.Outbox); ok {
		r0 = returnFunc(ctx, batchSize, maxRetries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]outbox.Outbox)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, batchSize, maxRetries)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockoutboxer_QueryUnprocessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryUnprocessed'
type mockoutboxer_QueryUnprocessed_Call struct {
	*mock.Call
}

// QueryUnprocessed is a helper method to define mock.On call
//   - ctx context.Context
//   - batchSize int
//   - maxRetries int
func (_e *mockoutboxer_Expecter) QueryUnprocessed(ctx interface{}, batchSize interface{}, maxRetries interface{}) *mockoutboxer_QueryUnprocessed_Call {
	return &mockoutboxer_QueryUnprocessed_Call{Call: _e.mock.On("QueryUnprocessed", ctx, batchSize, maxRetries)}
}

func (_c *mockoutboxer_QueryUnprocessed_Call) Run(run func(ctx context.Context, batchSize int, maxRetries int)) *mockoutboxer_QueryUnprocessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockoutboxer_QueryUnprocessed_Call) Return(outboxs []outbox.Outbox, err error) *mockoutboxer_QueryUnprocessed_Call {
	_c.Call.Return(outboxs, err)
	return _c
}

func (_c *mockoutboxer_QueryUnprocessed_Call) RunAndReturn(run func(ctx context.Context, batchSize int, maxRetries int) ([]outbox.Outbox, error)) *mockoutboxer_QueryUnprocessed_Call {
	_c.Call.Return(run)
	return _c
}
