// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package eventbus_test

import (
	"context"

	"github.com/Housiadas/cerberus/internal/core/audit"
	"github.com/Housiadas/cerberus/internal/core/outbox"
	mock "github.com/stretchr/testify/mock"
)

// newMockoutboxer creates a new instance of mockoutboxer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockoutboxer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockoutboxer {
	mock := &mockoutboxer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockoutboxer is an autogenerated mock type for the outboxer type
type mockoutboxer struct {
	mock.Mock
}

type mockoutboxer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockoutboxer) EXPECT() *mockoutboxer_Expecter {
	return &mockoutboxer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockoutboxer
func (_mock *mockoutboxer) Create(ctx context.Context, outbox1 outbox.NewOutbox) error {
	ret := _mock.Called(ctx, outbox1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbox.NewOutbox) error); ok {
		r0 = returnFunc(ctx, outbox1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockoutboxer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockoutboxer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - outbox1 outbox.NewOutbox
func (_e *mockoutboxer_Expecter) Create(ctx interface{}, outbox1 interface{}) *mockoutboxer_Create_Call {
	return &mockoutboxer_Create_Call{Call: _e.mock.On("Create", ctx, outbox1)}
}

func (_c *mockoutboxer_Create_Call) Run(run func(ctx context.Context, outbox1 outbox.NewOutbox)) *mockoutboxer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbox.NewOutbox
		if args[1] != nil {
			arg1 = args[1].(outbox.NewOutbox)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockoutboxer_Create_Call) Return(err error) *mockoutboxer_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockoutboxer_Create_Call) RunAndReturn(run func(ctx context.Context, outbox1 outbox.NewOutbox) error) *mockoutboxer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// newMockauditer creates a new instance of mockauditer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockauditer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockauditer {
	mock := &mockauditer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockauditer is an autogenerated mock type for the auditer type
type mockauditer struct {
	mock.Mock
}

type mockauditer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockauditer) EXPECT() *mockauditer_Expecter {
	return &mockauditer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockauditer
func (_mock *mockauditer) Create(ctx context.Context, audit1 audit.NewAudit) (audit.Audit, error) {
	ret := _mock.Called(ctx, audit1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 audit.Audit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, audit.NewAudit) (audit.Audit, error)); ok {
		return returnFunc(ctx, audit1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, audit.NewAudit) audit.Audit); ok {
		r0 = returnFunc(ctx, audit1)
	} else {
		r0 = ret.Get(0).(audit.Audit)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, audit.NewAudit) error); ok {
		r1 = returnFunc(ctx, audit1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockauditer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockauditer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - audit1 audit.NewAudit
func (_e *mockauditer_Expecter) Create(ctx interface{}, audit1 interface{}) *mockauditer_Create_Call {
	return &mockauditer_Create_Call{Call: _e.mock.On("Create", ctx, audit1)}
}

func (_c *mockauditer_Create_Call) Run(run func(ctx context.Context, audit1 audit.NewAudit)) *mockauditer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 audit.NewAudit
		if args[1] != nil {
			arg1 = args[1].(audit.NewAudit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockauditer_Create_Call) Return(audit11 audit.Audit, err error) *mockauditer_Create_Call {
	_c.Call.Return(audit11, err)
	return _c
}

func (_c *mockauditer_Create_Call) RunAndReturn(run func(ctx context.Context, audit1 audit.NewAudit) (audit.Audit, error)) *mockauditer_Create_Call {
	_c.Call.Return(run)
	return _c
}
