version: "2"
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - wsl
    - funlen
    - mnd
    - varnamelen
    - depguard
    - ireturn
    - exhaustruct
    - gosec
    - gochecknoglobals
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: strict
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
      - linters:
          - revive
        text: "var-naming: don't use an underscore in package name"
      - linters:
          - revive
        text: "var-naming: avoid package names that conflict"
      - path-except: _test\.go
        linters:
          - forbidigo
      - path: internal/hmac/
        text: "weak cryptographic primitive"
        linters:
          - gosec
      # Exclude some `staticcheck` messages.
      - linters:
          - staticcheck
        text: "SA9003:"
      # Exclude `lll` issues for long lines with `go:generate`.
      - linters:
          - lll
        source: "^//go:generate "
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  exclusions:
    warn-unused: true
    generated: strict
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
output:
  show-stats: true
run:
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 2
  tests: false
  modules-download-mode: vendor
