// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package audit_test

import (
	"context"
	"time"

	"github.com/Housiadas/cerberus/db/sqlc"
	"github.com/Housiadas/cerberus/pkg/cursor"
	"github.com/Housiadas/cerberus/pkg/order"
	mock "github.com/stretchr/testify/mock"
)

// newMockclock creates a new instance of mockclock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockclock(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockclock {
	mock := &mockclock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockclock is an autogenerated mock type for the clock type
type mockclock struct {
	mock.Mock
}

type mockclock_Expecter struct {
	mock *mock.Mock
}

func (_m *mockclock) EXPECT() *mockclock_Expecter {
	return &mockclock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type mockclock
func (_mock *mockclock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// mockclock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type mockclock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *mockclock_Expecter) Now() *mockclock_Now_Call {
	return &mockclock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *mockclock_Now_Call) Run(run func()) *mockclock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockclock_Now_Call) Return(time1 time.Time) *mockclock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *mockclock_Now_Call) RunAndReturn(run func() time.Time) *mockclock_Now_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstorer creates a new instance of mockstorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstorer {
	mock := &mockstorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstorer is an autogenerated mock type for the storer type
type mockstorer struct {
	mock.Mock
}

type mockstorer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstorer) EXPECT() *mockstorer_Expecter {
	return &mockstorer_Expecter{mock: &_m.Mock}
}

// CreateAudit provides a mock function for the type mockstorer
func (_mock *mockstorer) CreateAudit(ctx context.Context, arg db.CreateAuditParams) (db.Audit, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateAudit")
	}

	var r0 db.Audit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateAuditParams) (db.Audit, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateAuditParams) db.Audit); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Audit)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateAuditParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstorer_CreateAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAudit'
type mockstorer_CreateAudit_Call struct {
	*mock.Call
}

// CreateAudit is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateAuditParams
func (_e *mockstorer_Expecter) CreateAudit(ctx interface{}, arg interface{}) *mockstorer_CreateAudit_Call {
	return &mockstorer_CreateAudit_Call{Call: _e.mock.On("CreateAudit", ctx, arg)}
}

func (_c *mockstorer_CreateAudit_Call) Run(run func(ctx context.Context, arg db.CreateAuditParams)) *mockstorer_CreateAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateAuditParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateAuditParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_CreateAudit_Call) Return(audit db.Audit, err error) *mockstorer_CreateAudit_Call {
	_c.Call.Return(audit, err)
	return _c
}

func (_c *mockstorer_CreateAudit_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateAuditParams) (db.Audit, error)) *mockstorer_CreateAudit_Call {
	_c.Call.Return(run)
	return _c
}

// QueryAudits provides a mock function for the type mockstorer
func (_mock *mockstorer) QueryAudits(ctx context.Context, filter db.AuditQueryFilter, orderBy order.By, cur cursor.Cursor) ([]db.Audit, error) {
	ret := _mock.Called(ctx, filter, orderBy, cur)

	if len(ret) == 0 {
		panic("no return value specified for QueryAudits")
	}

	var r0 []db.Audit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.AuditQueryFilter, order.By, cursor.Cursor) ([]db.Audit, error)); ok {
		return returnFunc(ctx, filter, orderBy, cur)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.AuditQueryFilter, order.By, cursor.Cursor) []db.Audit); ok {
		r0 = returnFunc(ctx, filter, orderBy, cur)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Audit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.AuditQueryFilter, order.By, cursor.Cursor) error); ok {
		r1 = returnFunc(ctx, filter, orderBy, cur)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstorer_QueryAudits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryAudits'
type mockstorer_QueryAudits_Call struct {
	*mock.Call
}

// QueryAudits is a helper method to define mock.On call
//   - ctx context.Context
//   - filter db.AuditQueryFilter
//   - orderBy order.By
//   - cur cursor.Cursor
func (_e *mockstorer_Expecter) QueryAudits(ctx interface{}, filter interface{}, orderBy interface{}, cur interface{}) *mockstorer_QueryAudits_Call {
	return &mockstorer_QueryAudits_Call{Call: _e.mock.On("QueryAudits", ctx, filter, orderBy, cur)}
}

func (_c *mockstorer_QueryAudits_Call) Run(run func(ctx context.Context, filter db.AuditQueryFilter, orderBy order.By, cur cursor.Cursor)) *mockstorer_QueryAudits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.AuditQueryFilter
		if args[1] != nil {
			arg1 = args[1].(db.AuditQueryFilter)
		}
		var arg2 order.By
		if args[2] != nil {
			arg2 = args[2].(order.By)
		}
		var arg3 cursor.Cursor
		if args[3] != nil {
			arg3 = args[3].(cursor.Cursor)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockstorer_QueryAudits_Call) Return(audits []db.Audit, err error) *mockstorer_QueryAudits_Call {
	_c.Call.Return(audits, err)
	return _c
}

func (_c *mockstorer_QueryAudits_Call) RunAndReturn(run func(ctx context.Context, filter db.AuditQueryFilter, orderBy order.By, cur cursor.Cursor) ([]db.Audit, error)) *mockstorer_QueryAudits_Call {
	_c.Call.Return(run)
	return _c
}
