// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user_roles

import (
	"context"

	"github.com/Housiadas/cerberus/pkg/pgsql"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// NewWithTx provides a mock function for the type MockStorer
func (_mock *MockStorer) NewWithTx(tx pgsql.CommitRollbacker) (Storer, error) {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for NewWithTx")
	}

	var r0 Storer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgsql.CommitRollbacker) (Storer, error)); ok {
		return returnFunc(tx)
	}
	if returnFunc, ok := ret.Get(0).(func(pgsql.CommitRollbacker) Storer); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Storer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgsql.CommitRollbacker) error); ok {
		r1 = returnFunc(tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Add provides a mock function for the type MockStorer
func (_mock *MockStorer) Add(ctx context.Context, userID uuid.UUID, roleID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Remove provides a mock function for the type MockStorer
func (_mock *MockStorer) Remove(ctx context.Context, userID uuid.UUID, roleID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}
