// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user_roles_test

import (
	"context"

	"github.com/Housiadas/cerberus/db/sqlc"
	"github.com/Housiadas/cerberus/internal/types/event"
	mock "github.com/stretchr/testify/mock"
)

// newMockdispatcher creates a new instance of mockdispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdispatcher {
	mock := &mockdispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdispatcher is an autogenerated mock type for the dispatcher type
type mockdispatcher struct {
	mock.Mock
}

type mockdispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdispatcher) EXPECT() *mockdispatcher_Expecter {
	return &mockdispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type mockdispatcher
func (_mock *mockdispatcher) Dispatch(ctx context.Context, ev event.DomainEvent) error {
	ret := _mock.Called(ctx, ev)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, event.DomainEvent) error); ok {
		r0 = returnFunc(ctx, ev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type mockdispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - ev event.DomainEvent
func (_e *mockdispatcher_Expecter) Dispatch(ctx interface{}, ev interface{}) *mockdispatcher_Dispatch_Call {
	return &mockdispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, ev)}
}

func (_c *mockdispatcher_Dispatch_Call) Run(run func(ctx context.Context, ev event.DomainEvent)) *mockdispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 event.DomainEvent
		if args[1] != nil {
			arg1 = args[1].(event.DomainEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdispatcher_Dispatch_Call) Return(err error) *mockdispatcher_Dispatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdispatcher_Dispatch_Call) RunAndReturn(run func(ctx context.Context, ev event.DomainEvent) error) *mockdispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// newMocktransactor creates a new instance of mocktransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktransactor {
	mock := &mocktransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocktransactor is an autogenerated mock type for the transactor type
type mocktransactor struct {
	mock.Mock
}

type mocktransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktransactor) EXPECT() *mocktransactor_Expecter {
	return &mocktransactor_Expecter{mock: &_m.Mock}
}

// RunInTx provides a mock function for the type mocktransactor
func (_mock *mocktransactor) RunInTx(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunInTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocktransactor_RunInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInTx'
type mocktransactor_RunInTx_Call struct {
	*mock.Call
}

// RunInTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *mocktransactor_Expecter) RunInTx(ctx interface{}, fn interface{}) *mocktransactor_RunInTx_Call {
	return &mocktransactor_RunInTx_Call{Call: _e.mock.On("RunInTx", ctx, fn)}
}

func (_c *mocktransactor_RunInTx_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *mocktransactor_RunInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocktransactor_RunInTx_Call) Return(err error) *mocktransactor_RunInTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocktransactor_RunInTx_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *mocktransactor_RunInTx_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstorer creates a new instance of mockstorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstorer {
	mock := &mockstorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstorer is an autogenerated mock type for the storer type
type mockstorer struct {
	mock.Mock
}

type mockstorer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstorer) EXPECT() *mockstorer_Expecter {
	return &mockstorer_Expecter{mock: &_m.Mock}
}

// CreateUserRole provides a mock function for the type mockstorer
func (_mock *mockstorer) CreateUserRole(ctx context.Context, arg db.CreateUserRoleParams) (db.UserRole, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserRole")
	}

	var r0 db.UserRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateUserRoleParams) (db.UserRole, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateUserRoleParams) db.UserRole); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.UserRole)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateUserRoleParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstorer_CreateUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserRole'
type mockstorer_CreateUserRole_Call struct {
	*mock.Call
}

// CreateUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateUserRoleParams
func (_e *mockstorer_Expecter) CreateUserRole(ctx interface{}, arg interface{}) *mockstorer_CreateUserRole_Call {
	return &mockstorer_CreateUserRole_Call{Call: _e.mock.On("CreateUserRole", ctx, arg)}
}

func (_c *mockstorer_CreateUserRole_Call) Run(run func(ctx context.Context, arg db.CreateUserRoleParams)) *mockstorer_CreateUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateUserRoleParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateUserRoleParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_CreateUserRole_Call) Return(userRole db.UserRole, err error) *mockstorer_CreateUserRole_Call {
	_c.Call.Return(userRole, err)
	return _c
}

func (_c *mockstorer_CreateUserRole_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateUserRoleParams) (db.UserRole, error)) *mockstorer_CreateUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserRole provides a mock function for the type mockstorer
func (_mock *mockstorer) DeleteUserRole(ctx context.Context, arg db.DeleteUserRoleParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.DeleteUserRoleParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstorer_DeleteUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserRole'
type mockstorer_DeleteUserRole_Call struct {
	*mock.Call
}

// DeleteUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.DeleteUserRoleParams
func (_e *mockstorer_Expecter) DeleteUserRole(ctx interface{}, arg interface{}) *mockstorer_DeleteUserRole_Call {
	return &mockstorer_DeleteUserRole_Call{Call: _e.mock.On("DeleteUserRole", ctx, arg)}
}

func (_c *mockstorer_DeleteUserRole_Call) Run(run func(ctx context.Context, arg db.DeleteUserRoleParams)) *mockstorer_DeleteUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.DeleteUserRoleParams
		if args[1] != nil {
			arg1 = args[1].(db.DeleteUserRoleParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_DeleteUserRole_Call) Return(err error) *mockstorer_DeleteUserRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstorer_DeleteUserRole_Call) RunAndReturn(run func(ctx context.Context, arg db.DeleteUserRoleParams) error) *mockstorer_DeleteUserRole_Call {
	_c.Call.Return(run)
	return _c
}
