apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "tempo.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ include "tempo.fullname" . }}
  http:
    - route:
        - destination:
            host: {{ include "tempo.fullname" . }}
            port:
              number: {{ .Values.service.httpPort }}
