// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package audit

import (
	"context"

	"github.com/Housiadas/cerberus/pkg/order"
	"github.com/Housiadas/cerberus/pkg/web"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockStorer
func (_mock *MockStorer) Count(ctx context.Context, filter QueryFilter) (int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, QueryFilter) (int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, QueryFilter) int); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, QueryFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockStorer_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - filter QueryFilter
func (_e *MockStorer_Expecter) Count(ctx interface{}, filter interface{}) *MockStorer_Count_Call {
	return &MockStorer_Count_Call{Call: _e.mock.On("Count", ctx, filter)}
}

func (_c *MockStorer_Count_Call) Run(run func(ctx context.Context, filter QueryFilter)) *MockStorer_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 QueryFilter
		if args[1] != nil {
			arg1 = args[1].(QueryFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Count_Call) Return(n int, err error) *MockStorer_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStorer_Count_Call) RunAndReturn(run func(ctx context.Context, filter QueryFilter) (int, error)) *MockStorer_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockStorer
func (_mock *MockStorer) Create(ctx context.Context, audit Audit) error {
	ret := _mock.Called(ctx, audit)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Audit) error); ok {
		r0 = returnFunc(ctx, audit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - audit Audit
func (_e *MockStorer_Expecter) Create(ctx interface{}, audit interface{}) *MockStorer_Create_Call {
	return &MockStorer_Create_Call{Call: _e.mock.On("Create", ctx, audit)}
}

func (_c *MockStorer_Create_Call) Run(run func(ctx context.Context, audit Audit)) *MockStorer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Audit
		if args[1] != nil {
			arg1 = args[1].(Audit)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Create_Call) Return(err error) *MockStorer_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Create_Call) RunAndReturn(run func(ctx context.Context, audit Audit) error) *MockStorer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockStorer
func (_mock *MockStorer) Query(ctx context.Context, filter QueryFilter, orderBy order.By, page web.Page) ([]Audit, error) {
	ret := _mock.Called(ctx, filter, orderBy, page)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []Audit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, QueryFilter, order.By, web.Page) ([]Audit, error)); ok {
		return returnFunc(ctx, filter, orderBy, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, QueryFilter, order.By, web.Page) []Audit); ok {
		r0 = returnFunc(ctx, filter, orderBy, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Audit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, QueryFilter, order.By, web.Page) error); ok {
		r1 = returnFunc(ctx, filter, orderBy, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockStorer_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - filter QueryFilter
//   - orderBy order.By
//   - page web.Page
func (_e *MockStorer_Expecter) Query(ctx interface{}, filter interface{}, orderBy interface{}, page interface{}) *MockStorer_Query_Call {
	return &MockStorer_Query_Call{Call: _e.mock.On("Query", ctx, filter, orderBy, page)}
}

func (_c *MockStorer_Query_Call) Run(run func(ctx context.Context, filter QueryFilter, orderBy order.By, page web.Page)) *MockStorer_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 QueryFilter
		if args[1] != nil {
			arg1 = args[1].(QueryFilter)
		}
		var arg2 order.By
		if args[2] != nil {
			arg2 = args[2].(order.By)
		}
		var arg3 web.Page
		if args[3] != nil {
			arg3 = args[3].(web.Page)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorer_Query_Call) Return(audits []Audit, err error) *MockStorer_Query_Call {
	_c.Call.Return(audits, err)
	return _c
}

func (_c *MockStorer_Query_Call) RunAndReturn(run func(ctx context.Context, filter QueryFilter, orderBy order.By, page web.Page) ([]Audit, error)) *MockStorer_Query_Call {
	_c.Call.Return(run)
	return _c
}
