// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reset_token_test

import (
	"context"
	"time"

	"github.com/Housiadas/cerberus/internal/core/reset_token"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockStorer
func (_mock *MockStorer) Create(ctx context.Context, token reset_token.ResetToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, reset_token.ResetToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token reset_token.ResetToken
func (_e *MockStorer_Expecter) Create(ctx interface{}, token interface{}) *MockStorer_Create_Call {
	return &MockStorer_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockStorer_Create_Call) Run(run func(ctx context.Context, token reset_token.ResetToken)) *MockStorer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 reset_token.ResetToken
		if args[1] != nil {
			arg1 = args[1].(reset_token.ResetToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Create_Call) Return(err error) *MockStorer_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Create_Call) RunAndReturn(run func(ctx context.Context, token reset_token.ResetToken) error) *MockStorer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockStorer
func (_mock *MockStorer) Delete(ctx context.Context, token reset_token.ResetToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, reset_token.ResetToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - token reset_token.ResetToken
func (_e *MockStorer_Expecter) Delete(ctx interface{}, token interface{}) *MockStorer_Delete_Call {
	return &MockStorer_Delete_Call{Call: _e.mock.On("Delete", ctx, token)}
}

func (_c *MockStorer_Delete_Call) Run(run func(ctx context.Context, token reset_token.ResetToken)) *MockStorer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 reset_token.ResetToken
		if args[1] != nil {
			arg1 = args[1].(reset_token.ResetToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Delete_Call) Return(err error) *MockStorer_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Delete_Call) RunAndReturn(run func(ctx context.Context, token reset_token.ResetToken) error) *MockStorer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// QueryByToken provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryByToken(ctx context.Context, token string) (reset_token.ResetToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for QueryByToken")
	}

	var r0 reset_token.ResetToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (reset_token.ResetToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) reset_token.ResetToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(reset_token.ResetToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryByToken'
type MockStorer_QueryByToken_Call struct {
	*mock.Call
}

// QueryByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockStorer_Expecter) QueryByToken(ctx interface{}, token interface{}) *MockStorer_QueryByToken_Call {
	return &MockStorer_QueryByToken_Call{Call: _e.mock.On("QueryByToken", ctx, token)}
}

func (_c *MockStorer_QueryByToken_Call) Run(run func(ctx context.Context, token string)) *MockStorer_QueryByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_QueryByToken_Call) Return(resetToken reset_token.ResetToken, err error) *MockStorer_QueryByToken_Call {
	_c.Call.Return(resetToken, err)
	return _c
}

func (_c *MockStorer_QueryByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (reset_token.ResetToken, error)) *MockStorer_QueryByToken_Call {
	_c.Call.Return(run)
	return _c
}

// newMockgenerator creates a new instance of mockgenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockgenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockgenerator {
	mock := &mockgenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockgenerator is an autogenerated mock type for the generator type
type mockgenerator struct {
	mock.Mock
}

type mockgenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockgenerator) EXPECT() *mockgenerator_Expecter {
	return &mockgenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type mockgenerator
func (_mock *mockgenerator) Generate() (uuid.UUID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uuid.UUID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockgenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type mockgenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *mockgenerator_Expecter) Generate() *mockgenerator_Generate_Call {
	return &mockgenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *mockgenerator_Generate_Call) Run(run func()) *mockgenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockgenerator_Generate_Call) Return(uUID uuid.UUID, err error) *mockgenerator_Generate_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *mockgenerator_Generate_Call) RunAndReturn(run func() (uuid.UUID, error)) *mockgenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockclock creates a new instance of mockclock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockclock(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockclock {
	mock := &mockclock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockclock is an autogenerated mock type for the clock type
type mockclock struct {
	mock.Mock
}

type mockclock_Expecter struct {
	mock *mock.Mock
}

func (_m *mockclock) EXPECT() *mockclock_Expecter {
	return &mockclock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type mockclock
func (_mock *mockclock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// mockclock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type mockclock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *mockclock_Expecter) Now() *mockclock_Now_Call {
	return &mockclock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *mockclock_Now_Call) Run(run func()) *mockclock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockclock_Now_Call) Return(time1 time.Time) *mockclock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *mockclock_Now_Call) RunAndReturn(run func() time.Time) *mockclock_Now_Call {
	_c.Call.Return(run)
	return _c
}
