// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package role_permissions_test

import (
	"context"

	"github.com/Housiadas/cerberus/internal/core/role_permissions"
	"github.com/Housiadas/cerberus/pkg/pgsql"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockStorer
func (_mock *MockStorer) Add(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID) error {
	ret := _mock.Called(ctx, roleID, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, roleID, permissionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockStorer_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
//   - permissionID uuid.UUID
func (_e *MockStorer_Expecter) Add(ctx interface{}, roleID interface{}, permissionID interface{}) *MockStorer_Add_Call {
	return &MockStorer_Add_Call{Call: _e.mock.On("Add", ctx, roleID, permissionID)}
}

func (_c *MockStorer_Add_Call) Run(run func(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID)) *MockStorer_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorer_Add_Call) Return(err error) *MockStorer_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Add_Call) RunAndReturn(run func(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID) error) *MockStorer_Add_Call {
	_c.Call.Return(run)
	return _c
}

// NewWithTx provides a mock function for the type MockStorer
func (_mock *MockStorer) NewWithTx(tx pgsql.CommitRollbacker) (role_permissions.Storer, error) {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for NewWithTx")
	}

	var r0 role_permissions.Storer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgsql.CommitRollbacker) (role_permissions.Storer, error)); ok {
		return returnFunc(tx)
	}
	if returnFunc, ok := ret.Get(0).(func(pgsql.CommitRollbacker) role_permissions.Storer); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(role_permissions.Storer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgsql.CommitRollbacker) error); ok {
		r1 = returnFunc(tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_NewWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewWithTx'
type MockStorer_NewWithTx_Call struct {
	*mock.Call
}

// NewWithTx is a helper method to define mock.On call
//   - tx pgsql.CommitRollbacker
func (_e *MockStorer_Expecter) NewWithTx(tx interface{}) *MockStorer_NewWithTx_Call {
	return &MockStorer_NewWithTx_Call{Call: _e.mock.On("NewWithTx", tx)}
}

func (_c *MockStorer_NewWithTx_Call) Run(run func(tx pgsql.CommitRollbacker)) *MockStorer_NewWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgsql.CommitRollbacker
		if args[0] != nil {
			arg0 = args[0].(pgsql.CommitRollbacker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorer_NewWithTx_Call) Return(storer role_permissions.Storer, err error) *MockStorer_NewWithTx_Call {
	_c.Call.Return(storer, err)
	return _c
}

func (_c *MockStorer_NewWithTx_Call) RunAndReturn(run func(tx pgsql.CommitRollbacker) (role_permissions.Storer, error)) *MockStorer_NewWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockStorer
func (_mock *MockStorer) Remove(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID) error {
	ret := _mock.Called(ctx, roleID, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, roleID, permissionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockStorer_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
//   - permissionID uuid.UUID
func (_e *MockStorer_Expecter) Remove(ctx interface{}, roleID interface{}, permissionID interface{}) *MockStorer_Remove_Call {
	return &MockStorer_Remove_Call{Call: _e.mock.On("Remove", ctx, roleID, permissionID)}
}

func (_c *MockStorer_Remove_Call) Run(run func(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID)) *MockStorer_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorer_Remove_Call) Return(err error) *MockStorer_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Remove_Call) RunAndReturn(run func(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID) error) *MockStorer_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// newMocklogger creates a new instance of mocklogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocklogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocklogger {
	mock := &mocklogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocklogger is an autogenerated mock type for the logger type
type mocklogger struct {
	mock.Mock
}

type mocklogger_Expecter struct {
	mock *mock.Mock
}

func (_m *mocklogger) EXPECT() *mocklogger_Expecter {
	return &mocklogger_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type mocklogger
func (_mock *mocklogger) Error(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type mocklogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Error(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Error_Call {
	return &mocklogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Error_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Error_Call) Return() *mocklogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Error_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type mocklogger
func (_mock *mocklogger) Info(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type mocklogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Info(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Info_Call {
	return &mocklogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Info_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Info_Call) Return() *mocklogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Info_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Info_Call {
	_c.Run(run)
	return _c
}
