// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package role_permissions_test

import (
	"context"

	"github.com/Housiadas/cerberus/db/sqlc"
	"github.com/Housiadas/cerberus/internal/types/event"
	mock "github.com/stretchr/testify/mock"
)

// newMockdispatcher creates a new instance of mockdispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdispatcher {
	mock := &mockdispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdispatcher is an autogenerated mock type for the dispatcher type
type mockdispatcher struct {
	mock.Mock
}

type mockdispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdispatcher) EXPECT() *mockdispatcher_Expecter {
	return &mockdispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type mockdispatcher
func (_mock *mockdispatcher) Dispatch(ctx context.Context, ev event.DomainEvent) error {
	ret := _mock.Called(ctx, ev)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, event.DomainEvent) error); ok {
		r0 = returnFunc(ctx, ev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type mockdispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - ev event.DomainEvent
func (_e *mockdispatcher_Expecter) Dispatch(ctx interface{}, ev interface{}) *mockdispatcher_Dispatch_Call {
	return &mockdispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, ev)}
}

func (_c *mockdispatcher_Dispatch_Call) Run(run func(ctx context.Context, ev event.DomainEvent)) *mockdispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 event.DomainEvent
		if args[1] != nil {
			arg1 = args[1].(event.DomainEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdispatcher_Dispatch_Call) Return(err error) *mockdispatcher_Dispatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdispatcher_Dispatch_Call) RunAndReturn(run func(ctx context.Context, ev event.DomainEvent) error) *mockdispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// newMocktransactor creates a new instance of mocktransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktransactor {
	mock := &mocktransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocktransactor is an autogenerated mock type for the transactor type
type mocktransactor struct {
	mock.Mock
}

type mocktransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktransactor) EXPECT() *mocktransactor_Expecter {
	return &mocktransactor_Expecter{mock: &_m.Mock}
}

// RunInTx provides a mock function for the type mocktransactor
func (_mock *mocktransactor) RunInTx(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunInTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocktransactor_RunInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInTx'
type mocktransactor_RunInTx_Call struct {
	*mock.Call
}

// RunInTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *mocktransactor_Expecter) RunInTx(ctx interface{}, fn interface{}) *mocktransactor_RunInTx_Call {
	return &mocktransactor_RunInTx_Call{Call: _e.mock.On("RunInTx", ctx, fn)}
}

func (_c *mocktransactor_RunInTx_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *mocktransactor_RunInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocktransactor_RunInTx_Call) Return(err error) *mocktransactor_RunInTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocktransactor_RunInTx_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *mocktransactor_RunInTx_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstorer creates a new instance of mockstorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstorer {
	mock := &mockstorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstorer is an autogenerated mock type for the storer type
type mockstorer struct {
	mock.Mock
}

type mockstorer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstorer) EXPECT() *mockstorer_Expecter {
	return &mockstorer_Expecter{mock: &_m.Mock}
}

// CreateRolePermission provides a mock function for the type mockstorer
func (_mock *mockstorer) CreateRolePermission(ctx context.Context, arg db.CreateRolePermissionParams) (db.RolePermission, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRolePermission")
	}

	var r0 db.RolePermission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateRolePermissionParams) (db.RolePermission, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateRolePermissionParams) db.RolePermission); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.RolePermission)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateRolePermissionParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstorer_CreateRolePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRolePermission'
type mockstorer_CreateRolePermission_Call struct {
	*mock.Call
}

// CreateRolePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateRolePermissionParams
func (_e *mockstorer_Expecter) CreateRolePermission(ctx interface{}, arg interface{}) *mockstorer_CreateRolePermission_Call {
	return &mockstorer_CreateRolePermission_Call{Call: _e.mock.On("CreateRolePermission", ctx, arg)}
}

func (_c *mockstorer_CreateRolePermission_Call) Run(run func(ctx context.Context, arg db.CreateRolePermissionParams)) *mockstorer_CreateRolePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateRolePermissionParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateRolePermissionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_CreateRolePermission_Call) Return(rolePermission db.RolePermission, err error) *mockstorer_CreateRolePermission_Call {
	_c.Call.Return(rolePermission, err)
	return _c
}

func (_c *mockstorer_CreateRolePermission_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateRolePermissionParams) (db.RolePermission, error)) *mockstorer_CreateRolePermission_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRolePermission provides a mock function for the type mockstorer
func (_mock *mockstorer) DeleteRolePermission(ctx context.Context, arg db.DeleteRolePermissionParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRolePermission")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.DeleteRolePermissionParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstorer_DeleteRolePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRolePermission'
type mockstorer_DeleteRolePermission_Call struct {
	*mock.Call
}

// DeleteRolePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.DeleteRolePermissionParams
func (_e *mockstorer_Expecter) DeleteRolePermission(ctx interface{}, arg interface{}) *mockstorer_DeleteRolePermission_Call {
	return &mockstorer_DeleteRolePermission_Call{Call: _e.mock.On("DeleteRolePermission", ctx, arg)}
}

func (_c *mockstorer_DeleteRolePermission_Call) Run(run func(ctx context.Context, arg db.DeleteRolePermissionParams)) *mockstorer_DeleteRolePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.DeleteRolePermissionParams
		if args[1] != nil {
			arg1 = args[1].(db.DeleteRolePermissionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_DeleteRolePermission_Call) Return(err error) *mockstorer_DeleteRolePermission_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstorer_DeleteRolePermission_Call) RunAndReturn(run func(ctx context.Context, arg db.DeleteRolePermissionParams) error) *mockstorer_DeleteRolePermission_Call {
	_c.Call.Return(run)
	return _c
}
