// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package logger

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type MockLogger
func (_mock *MockLogger) Debug(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Debug(ctx interface{}, msg interface{}, args ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(ctx context.Context, msg string, args ...any)) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Debugc provides a mock function for the type MockLogger
func (_mock *MockLogger) Debugc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// MockLogger_Debugc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugc'
type MockLogger_Debugc_Call struct {
	*mock.Call
}

// Debugc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Debugc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *MockLogger_Debugc_Call {
	return &MockLogger_Debugc_Call{Call: _e.mock.On("Debugc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *MockLogger_Debugc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *MockLogger_Debugc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockLogger_Debugc_Call) Return() *MockLogger_Debugc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debugc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *MockLogger_Debugc_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Error(ctx interface{}, msg interface{}, args ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(ctx context.Context, msg string, args ...any)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Errorc provides a mock function for the type MockLogger
func (_mock *MockLogger) Errorc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// MockLogger_Errorc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorc'
type MockLogger_Errorc_Call struct {
	*mock.Call
}

// Errorc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Errorc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *MockLogger_Errorc_Call {
	return &MockLogger_Errorc_Call{Call: _e.mock.On("Errorc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *MockLogger_Errorc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *MockLogger_Errorc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockLogger_Errorc_Call) Return() *MockLogger_Errorc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Errorc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *MockLogger_Errorc_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Info(ctx interface{}, msg interface{}, args ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(ctx context.Context, msg string, args ...any)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// Infoc provides a mock function for the type MockLogger
func (_mock *MockLogger) Infoc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// MockLogger_Infoc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infoc'
type MockLogger_Infoc_Call struct {
	*mock.Call
}

// Infoc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Infoc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *MockLogger_Infoc_Call {
	return &MockLogger_Infoc_Call{Call: _e.mock.On("Infoc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *MockLogger_Infoc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *MockLogger_Infoc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockLogger_Infoc_Call) Return() *MockLogger_Infoc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Infoc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *MockLogger_Infoc_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockLogger
func (_mock *MockLogger) Warn(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Warn(ctx interface{}, msg interface{}, args ...interface{}) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockLogger_Warn_Call) Run(run func(ctx context.Context, msg string, args ...any)) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}

// Warnc provides a mock function for the type MockLogger
func (_mock *MockLogger) Warnc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// MockLogger_Warnc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warnc'
type MockLogger_Warnc_Call struct {
	*mock.Call
}

// Warnc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Warnc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *MockLogger_Warnc_Call {
	return &MockLogger_Warnc_Call{Call: _e.mock.On("Warnc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *MockLogger_Warnc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *MockLogger_Warnc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockLogger_Warnc_Call) Return() *MockLogger_Warnc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warnc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *MockLogger_Warnc_Call {
	_c.Run(run)
	return _c
}
