// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAudit = `-- name: CreateAudit :one
INSERT INTO audit (
    id,
    obj_id,
    obj_entity,
    obj_name,
    actor_id,
    action,
    data,
    message,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
) RETURNING id, obj_id, obj_entity, obj_name, actor_id, action, data, message, created_at
`

type CreateAuditParams struct {
	ID        uuid.UUID
	ObjID     uuid.UUID
	ObjEntity string
	ObjName   string
	ActorID   uuid.UUID
	Action    string
	Data      []byte
	Message   pgtype.Text
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CreateAudit(ctx context.Context, arg CreateAuditParams) (Audit, error) {
	row := q.db.QueryRow(ctx, createAudit,
		arg.ID,
		arg.ObjID,
		arg.ObjEntity,
		arg.ObjName,
		arg.ActorID,
		arg.Action,
		arg.Data,
		arg.Message,
		arg.CreatedAt,
	)
	var i Audit
	err := row.Scan(
		&i.ID,
		&i.ObjID,
		&i.ObjEntity,
		&i.ObjName,
		&i.ActorID,
		&i.Action,
		&i.Data,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}
