// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID               uuid.UUID
	Name             string
	StripeCustomerID pgtype.Text
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
	DeletedAt        pgtype.Timestamp
}

type Audit struct {
	ID        uuid.UUID
	ObjID     uuid.UUID
	ObjEntity string
	ObjName   string
	ActorID   uuid.UUID
	Action    string
	Data      []byte
	Message   pgtype.Text
	CreatedAt pgtype.Timestamp
}

type BillingAddress struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	Line1      string
	Line2      pgtype.Text
	City       string
	State      pgtype.Text
	PostalCode string
	Country    string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type EmailNotificationOutbox struct {
	ID          uuid.UUID
	EventType   string
	ToEmail     string
	Payload     []byte
	RetryCount  int32
	CreatedAt   pgtype.Timestamp
	ProcessedAt pgtype.Timestamp
}

type Invoice struct {
	ID               uuid.UUID
	AccountID        uuid.UUID
	StripeInvoiceID  string
	StripeCustomerID string
	Status           string
	AmountDue        int64
	AmountPaid       int64
	Currency         string
	InvoiceUrl       pgtype.Text
	PeriodStart      pgtype.Timestamp
	PeriodEnd        pgtype.Timestamp
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type Outbox struct {
	ID          uuid.UUID
	EventType   string
	AggregateID uuid.UUID
	Topic       string
	Payload     []byte
	RetryCount  int32
	CreatedAt   pgtype.Timestamp
	ProcessedAt pgtype.Timestamp
}

type Payment struct {
	ID               uuid.UUID
	AccountID        uuid.UUID
	StripePaymentID  string
	StripeInvoiceID  pgtype.Text
	StripeCustomerID string
	Amount           int64
	Currency         string
	Status           string
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type Permission struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	Revoked   bool
}

type Refund struct {
	ID             uuid.UUID
	AccountID      uuid.UUID
	PaymentID      uuid.UUID
	StripeRefundID string
	Amount         int64
	Currency       string
	Status         string
	Reason         pgtype.Text
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type ResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	Used      bool
}

type Role struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type RolePermission struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
}

type Subscription struct {
	ID                   uuid.UUID
	AccountID            uuid.UUID
	StripeSubscriptionID string
	StripeCustomerID     string
	StripePriceID        string
	Status               string
	CurrentPeriodStart   pgtype.Timestamp
	CurrentPeriodEnd     pgtype.Timestamp
	CancelAtPeriodEnd    bool
	CanceledAt           pgtype.Timestamp
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
}

type User struct {
	ID           uuid.UUID
	AccountID    pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	Department   pgtype.Text
	Enabled      bool
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
}

type UserRole struct {
	UserID    uuid.UUID
	RoleID    uuid.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type VwUserRolesPermission struct {
	UserID         uuid.UUID
	UserName       string
	UserEmail      string
	AccountID      pgtype.UUID
	RoleID         uuid.UUID
	RoleName       string
	PermissionID   pgtype.UUID
	PermissionName pgtype.Text
}
