// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationOutbox = `-- name: CreateNotificationOutbox :one
INSERT INTO email_notification_outbox (
    id,
    event_type,
    to_email,
    payload,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, event_type, to_email, payload, retry_count, created_at, processed_at
`

type CreateNotificationOutboxParams struct {
	ID        uuid.UUID
	EventType string
	ToEmail   string
	Payload   []byte
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CreateNotificationOutbox(ctx context.Context, arg CreateNotificationOutboxParams) (EmailNotificationOutbox, error) {
	row := q.db.QueryRow(ctx, createNotificationOutbox,
		arg.ID,
		arg.EventType,
		arg.ToEmail,
		arg.Payload,
		arg.CreatedAt,
	)
	var i EmailNotificationOutbox
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.ToEmail,
		&i.Payload,
		&i.RetryCount,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const deleteProcessedNotificationOutbox = `-- name: DeleteProcessedNotificationOutbox :execrows
DELETE FROM email_notification_outbox
WHERE processed_at IS NOT NULL
  AND processed_at < $1::timestamp
`

func (q *Queries) DeleteProcessedNotificationOutbox(ctx context.Context, before pgtype.Timestamp) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProcessedNotificationOutbox, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUnprocessedNotificationOutbox = `-- name: GetUnprocessedNotificationOutbox :many
SELECT id, event_type, to_email, payload, retry_count, created_at, processed_at FROM email_notification_outbox
WHERE
retry_count < $2
AND processed_at IS NULL
ORDER BY created_at
LIMIT $1
`

type GetUnprocessedNotificationOutboxParams struct {
	Limit      int32
	MaxRetries int32
}

func (q *Queries) GetUnprocessedNotificationOutbox(ctx context.Context, arg GetUnprocessedNotificationOutboxParams) ([]EmailNotificationOutbox, error) {
	rows, err := q.db.Query(ctx, getUnprocessedNotificationOutbox, arg.Limit, arg.MaxRetries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailNotificationOutbox{}
	for rows.Next() {
		var i EmailNotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ToEmail,
			&i.Payload,
			&i.RetryCount,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementRetryNotificationOutbox = `-- name: IncrementRetryNotificationOutbox :exec
UPDATE email_notification_outbox
SET retry_count = retry_count + 1
WHERE id = ANY($1::uuid[])
`

func (q *Queries) IncrementRetryNotificationOutbox(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementRetryNotificationOutbox, ids)
	return err
}

const markProcessedNotificationOutbox = `-- name: MarkProcessedNotificationOutbox :exec
UPDATE email_notification_outbox
SET processed_at = $1
WHERE id = ANY($2::uuid[])
`

type MarkProcessedNotificationOutboxParams struct {
	ProcessedAt pgtype.Timestamp
	Ids         []uuid.UUID
}

func (q *Queries) MarkProcessedNotificationOutbox(ctx context.Context, arg MarkProcessedNotificationOutboxParams) error {
	_, err := q.db.Exec(ctx, markProcessedNotificationOutbox, arg.ProcessedAt, arg.Ids)
	return err
}
