// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOutbox = `-- name: CreateOutbox :one
INSERT INTO outbox (
    id,
    event_type,
    aggregate_id,
    topic,
    payload,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, event_type, aggregate_id, topic, payload, retry_count, created_at, processed_at
`

type CreateOutboxParams struct {
	ID          uuid.UUID
	EventType   string
	AggregateID uuid.UUID
	Topic       string
	Payload     []byte
	CreatedAt   pgtype.Timestamp
}

func (q *Queries) CreateOutbox(ctx context.Context, arg CreateOutboxParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, createOutbox,
		arg.ID,
		arg.EventType,
		arg.AggregateID,
		arg.Topic,
		arg.Payload,
		arg.CreatedAt,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateID,
		&i.Topic,
		&i.Payload,
		&i.RetryCount,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getUnprocessedOutbox = `-- name: GetUnprocessedOutbox :many
SELECT id, event_type, aggregate_id, topic, payload, retry_count, created_at, processed_at FROM outbox
WHERE retry_count < $2
AND processed_at IS NULL
ORDER BY created_at
LIMIT $1
`

type GetUnprocessedOutboxParams struct {
	Limit      int32
	MaxRetries int32
}

func (q *Queries) GetUnprocessedOutbox(ctx context.Context, arg GetUnprocessedOutboxParams) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getUnprocessedOutbox, arg.Limit, arg.MaxRetries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.Topic,
			&i.Payload,
			&i.RetryCount,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementRetryOutbox = `-- name: IncrementRetryOutbox :exec
UPDATE outbox
SET retry_count = retry_count + 1
WHERE id IN ($1)
`

func (q *Queries) IncrementRetryOutbox(ctx context.Context, ids uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementRetryOutbox, ids)
	return err
}

const markProcessedOutbox = `-- name: MarkProcessedOutbox :exec
UPDATE outbox
SET processed_at = $1
WHERE id = ANY($2::uuid[])
`

type MarkProcessedOutboxParams struct {
	ProcessedAt pgtype.Timestamp
	Ids         []uuid.UUID
}

func (q *Queries) MarkProcessedOutbox(ctx context.Context, arg MarkProcessedOutboxParams) error {
	_, err := q.db.Exec(ctx, markProcessedOutbox, arg.ProcessedAt, arg.Ids)
	return err
}
