// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (
    id,
    name,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, name, created_at, updated_at, deleted_at
`

type CreatePermissionParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
UPDATE permissions
SET deleted_at = NOW()
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) DeletePermission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT
    id,
    name,
    created_at,
    updated_at
FROM permissions
WHERE id = $1
AND deleted_at IS NULL
`

type GetPermissionByIDRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) GetPermissionByID(ctx context.Context, id uuid.UUID) (GetPermissionByIDRow, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i GetPermissionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE permissions
SET
    name = COALESCE($1, name),
    updated_at = COALESCE($2, updated_at)
WHERE id = $3
RETURNING id, name, created_at, updated_at, deleted_at
`

type UpdatePermissionParams struct {
	Name      pgtype.Text
	UpdatedAt pgtype.Timestamp
	ID        uuid.UUID
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, updatePermission, arg.Name, arg.UpdatedAt, arg.ID)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
