// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset_token.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createResetToken = `-- name: CreateResetToken :one
INSERT INTO reset_tokens
(
    id,
    user_id,
    token,
    used,
    expires_at,
    created_at
)
VALUES
(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, user_id, token, expires_at, created_at, used
`

type CreateResetTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	Used      bool
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CreateResetToken(ctx context.Context, arg CreateResetTokenParams) (ResetToken, error) {
	row := q.db.QueryRow(ctx, createResetToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.Used,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i ResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Used,
	)
	return i, err
}

const deleteResetToken = `-- name: DeleteResetToken :exec
DELETE
FROM reset_tokens
WHERE id = $1
`

func (q *Queries) DeleteResetToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResetToken, id)
	return err
}

const getResetTokenByToken = `-- name: GetResetTokenByToken :one
SELECT
    id,
    user_id,
    token,
    expires_at,
    created_at,
    used
FROM reset_tokens
WHERE token = $1
`

func (q *Queries) GetResetTokenByToken(ctx context.Context, token string) (ResetToken, error) {
	row := q.db.QueryRow(ctx, getResetTokenByToken, token)
	var i ResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Used,
	)
	return i, err
}
