// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_permission.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRolePermission = `-- name: CreateRolePermission :one
INSERT INTO role_permissions (
    role_id,
    permission_id,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4
) ON CONFLICT (role_id, permission_id) DO NOTHING RETURNING role_id, permission_id, created_at, updated_at, deleted_at
`

type CreateRolePermissionParams struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) (RolePermission, error) {
	row := q.db.QueryRow(ctx, createRolePermission,
		arg.RoleID,
		arg.PermissionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RolePermission
	err := row.Scan(
		&i.RoleID,
		&i.PermissionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRolePermission = `-- name: DeleteRolePermission :exec
DELETE FROM role_permissions
WHERE role_id = $1
AND permission_id = $2
`

type DeleteRolePermissionParams struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) DeleteRolePermission(ctx context.Context, arg DeleteRolePermissionParams) error {
	_, err := q.db.Exec(ctx, deleteRolePermission, arg.RoleID, arg.PermissionID)
	return err
}
