// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
    id,
    name,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, name, created_at, updated_at, deleted_at
`

type CreateRoleParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
UPDATE roles
SET deleted_at = NOW()
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT
    id,
    name,
    created_at,
    updated_at
FROM roles
WHERE id = $1
AND deleted_at IS NULL
`

type GetRoleByIDRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (GetRoleByIDRow, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i GetRoleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET
    name = COALESCE($1, name),
    updated_at = COALESCE($2, updated_at)
WHERE id = $3
RETURNING id, name, created_at, updated_at, deleted_at
`

type UpdateRoleParams struct {
	Name      pgtype.Text
	UpdatedAt pgtype.Timestamp
	ID        uuid.UUID
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.Name, arg.UpdatedAt, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
