// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    account_id,
    name,
    email,
    password_hash,
    department,
    enabled,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
) RETURNING id, account_id, name, email, password_hash, department, enabled, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	AccountID    pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	Department   pgtype.Text
	Enabled      bool
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Department,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Department,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, account_id, name, email, password_hash, department, enabled, created_at, updated_at, deleted_at
FROM users
WHERE email = $1
AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Department,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, account_id, name, email, password_hash, department, enabled, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Department,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = COALESCE($1, name),
    email = COALESCE($2, email),
    password_hash = COALESCE($3, password_hash),
    enabled = COALESCE($4, enabled),
    updated_at = COALESCE($5, updated_at)
WHERE id = $6
RETURNING id, account_id, name, email, password_hash, department, enabled, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	Name         pgtype.Text
	Email        pgtype.Text
	PasswordHash pgtype.Text
	Enabled      pgtype.Bool
	UpdatedAt    pgtype.Timestamp
	ID           uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Department,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
