// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package distributed_storage_test

import (
	"context"
	"time"

	"github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// newMockclient creates a new instance of mockclient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockclient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockclient {
	mock := &mockclient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockclient is an autogenerated mock type for the client type
type mockclient struct {
	mock.Mock
}

type mockclient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockclient) EXPECT() *mockclient_Expecter {
	return &mockclient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type mockclient
func (_mock *mockclient) Get(ctx context.Context, key string) *redis.StringCmd {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *redis.StringCmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *redis.StringCmd); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StringCmd)
		}
	}
	return r0
}

// mockclient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockclient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *mockclient_Expecter) Get(ctx interface{}, key interface{}) *mockclient_Get_Call {
	return &mockclient_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *mockclient_Get_Call) Run(run func(ctx context.Context, key string)) *mockclient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockclient_Get_Call) Return(stringCmd *redis.StringCmd) *mockclient_Get_Call {
	_c.Call.Return(stringCmd)
	return _c
}

func (_c *mockclient_Get_Call) RunAndReturn(run func(ctx context.Context, key string) *redis.StringCmd) *mockclient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// MGet provides a mock function for the type mockclient
func (_mock *mockclient) MGet(ctx context.Context, keys ...string) *redis.SliceCmd {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MGet")
	}

	var r0 *redis.SliceCmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) *redis.SliceCmd); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.SliceCmd)
		}
	}
	return r0
}

// mockclient_MGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MGet'
type mockclient_MGet_Call struct {
	*mock.Call
}

// MGet is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *mockclient_Expecter) MGet(ctx interface{}, keys ...interface{}) *mockclient_MGet_Call {
	return &mockclient_MGet_Call{Call: _e.mock.On("MGet",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *mockclient_MGet_Call) Run(run func(ctx context.Context, keys ...string)) *mockclient_MGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *mockclient_MGet_Call) Return(sliceCmd *redis.SliceCmd) *mockclient_MGet_Call {
	_c.Call.Return(sliceCmd)
	return _c
}

func (_c *mockclient_MGet_Call) RunAndReturn(run func(ctx context.Context, keys ...string) *redis.SliceCmd) *mockclient_MGet_Call {
	_c.Call.Return(run)
	return _c
}

// Pipeline provides a mock function for the type mockclient
func (_mock *mockclient) Pipeline() redis.Pipeliner {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pipeline")
	}

	var r0 redis.Pipeliner
	if returnFunc, ok := ret.Get(0).(func() redis.Pipeliner); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.Pipeliner)
		}
	}
	return r0
}

// mockclient_Pipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pipeline'
type mockclient_Pipeline_Call struct {
	*mock.Call
}

// Pipeline is a helper method to define mock.On call
func (_e *mockclient_Expecter) Pipeline() *mockclient_Pipeline_Call {
	return &mockclient_Pipeline_Call{Call: _e.mock.On("Pipeline")}
}

func (_c *mockclient_Pipeline_Call) Run(run func()) *mockclient_Pipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockclient_Pipeline_Call) Return(pipeliner redis.Pipeliner) *mockclient_Pipeline_Call {
	_c.Call.Return(pipeliner)
	return _c
}

func (_c *mockclient_Pipeline_Call) RunAndReturn(run func() redis.Pipeliner) *mockclient_Pipeline_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type mockclient
func (_mock *mockclient) Set(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 *redis.StatusCmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) *redis.StatusCmd); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StatusCmd)
		}
	}
	return r0
}

// mockclient_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type mockclient_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - expiration time.Duration
func (_e *mockclient_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *mockclient_Set_Call {
	return &mockclient_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *mockclient_Set_Call) Run(run func(ctx context.Context, key string, value any, expiration time.Duration)) *mockclient_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockclient_Set_Call) Return(statusCmd *redis.StatusCmd) *mockclient_Set_Call {
	_c.Call.Return(statusCmd)
	return _c
}

func (_c *mockclient_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd) *mockclient_Set_Call {
	_c.Call.Return(run)
	return _c
}
