// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package refund_test

import (
	"context"

	"github.com/Housiadas/cerberus/internal/core/refund"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockStorer
func (_mock *MockStorer) Create(ctx context.Context, ref refund.Refund) error {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, refund.Refund) error); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ref refund.Refund
func (_e *MockStorer_Expecter) Create(ctx interface{}, ref interface{}) *MockStorer_Create_Call {
	return &MockStorer_Create_Call{Call: _e.mock.On("Create", ctx, ref)}
}

func (_c *MockStorer_Create_Call) Run(run func(ctx context.Context, ref refund.Refund)) *MockStorer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 refund.Refund
		if args[1] != nil {
			arg1 = args[1].(refund.Refund)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Create_Call) Return(err error) *MockStorer_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Create_Call) RunAndReturn(run func(ctx context.Context, ref refund.Refund) error) *MockStorer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// QueryByAccountID provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryByAccountID(ctx context.Context, accountID uuid.UUID) ([]refund.Refund, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for QueryByAccountID")
	}

	var r0 []refund.Refund
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]refund.Refund, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []refund.Refund); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]refund.Refund)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryByAccountID'
type MockStorer_QueryByAccountID_Call struct {
	*mock.Call
}

// QueryByAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
func (_e *MockStorer_Expecter) QueryByAccountID(ctx interface{}, accountID interface{}) *MockStorer_QueryByAccountID_Call {
	return &MockStorer_QueryByAccountID_Call{Call: _e.mock.On("QueryByAccountID", ctx, accountID)}
}

func (_c *MockStorer_QueryByAccountID_Call) Run(run func(ctx context.Context, accountID uuid.UUID)) *MockStorer_QueryByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_QueryByAccountID_Call) Return(refunds []refund.Refund, err error) *MockStorer_QueryByAccountID_Call {
	_c.Call.Return(refunds, err)
	return _c
}

func (_c *MockStorer_QueryByAccountID_Call) RunAndReturn(run func(ctx context.Context, accountID uuid.UUID) ([]refund.Refund, error)) *MockStorer_QueryByAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// newMocklogger creates a new instance of mocklogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocklogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocklogger {
	mock := &mocklogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocklogger is an autogenerated mock type for the logger type
type mocklogger struct {
	mock.Mock
}

type mocklogger_Expecter struct {
	mock *mock.Mock
}

func (_m *mocklogger) EXPECT() *mocklogger_Expecter {
	return &mocklogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type mocklogger
func (_mock *mocklogger) Debug(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type mocklogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Debug(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Debug_Call {
	return &mocklogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Debug_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Debug_Call) Return() *mocklogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Debug_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Debugc provides a mock function for the type mocklogger
func (_mock *mocklogger) Debugc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Debugc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugc'
type mocklogger_Debugc_Call struct {
	*mock.Call
}

// Debugc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Debugc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Debugc_Call {
	return &mocklogger_Debugc_Call{Call: _e.mock.On("Debugc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Debugc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Debugc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Debugc_Call) Return() *mocklogger_Debugc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Debugc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Debugc_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type mocklogger
func (_mock *mocklogger) Error(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type mocklogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Error(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Error_Call {
	return &mocklogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Error_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Error_Call) Return() *mocklogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Error_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Error_Call {
	_c.Run(run)
	return _c
}

// Errorc provides a mock function for the type mocklogger
func (_mock *mocklogger) Errorc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Errorc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorc'
type mocklogger_Errorc_Call struct {
	*mock.Call
}

// Errorc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Errorc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Errorc_Call {
	return &mocklogger_Errorc_Call{Call: _e.mock.On("Errorc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Errorc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Errorc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Errorc_Call) Return() *mocklogger_Errorc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Errorc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Errorc_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type mocklogger
func (_mock *mocklogger) Info(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type mocklogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Info(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Info_Call {
	return &mocklogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Info_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Info_Call) Return() *mocklogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Info_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Info_Call {
	_c.Run(run)
	return _c
}

// Infoc provides a mock function for the type mocklogger
func (_mock *mocklogger) Infoc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Infoc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infoc'
type mocklogger_Infoc_Call struct {
	*mock.Call
}

// Infoc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Infoc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Infoc_Call {
	return &mocklogger_Infoc_Call{Call: _e.mock.On("Infoc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Infoc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Infoc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Infoc_Call) Return() *mocklogger_Infoc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Infoc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Infoc_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type mocklogger
func (_mock *mocklogger) Warn(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type mocklogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Warn(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Warn_Call {
	return &mocklogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Warn_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Warn_Call) Return() *mocklogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Warn_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Warn_Call {
	_c.Run(run)
	return _c
}

// Warnc provides a mock function for the type mocklogger
func (_mock *mocklogger) Warnc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Warnc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warnc'
type mocklogger_Warnc_Call struct {
	*mock.Call
}

// Warnc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Warnc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Warnc_Call {
	return &mocklogger_Warnc_Call{Call: _e.mock.On("Warnc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Warnc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Warnc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Warnc_Call) Return() *mocklogger_Warnc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Warnc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Warnc_Call {
	_c.Run(run)
	return _c
}
