// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package permissionmocks

import (
	"context"

	"github.com/Housiadas/cerberus/internal/core/permission"
	"github.com/Housiadas/cerberus/pkg/cursor"
	"github.com/Housiadas/cerberus/pkg/order"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockStorer
func (_mock *MockStorer) Create(ctx context.Context, p permission.Permission) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, permission.Permission) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p permission.Permission
func (_e *MockStorer_Expecter) Create(ctx interface{}, p interface{}) *MockStorer_Create_Call {
	return &MockStorer_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockStorer_Create_Call) Run(run func(ctx context.Context, p permission.Permission)) *MockStorer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 permission.Permission
		if args[1] != nil {
			arg1 = args[1].(permission.Permission)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Create_Call) Return(err error) *MockStorer_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Create_Call) RunAndReturn(run func(ctx context.Context, p permission.Permission) error) *MockStorer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockStorer
func (_mock *MockStorer) Delete(ctx context.Context, p permission.Permission) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, permission.Permission) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - p permission.Permission
func (_e *MockStorer_Expecter) Delete(ctx interface{}, p interface{}) *MockStorer_Delete_Call {
	return &MockStorer_Delete_Call{Call: _e.mock.On("Delete", ctx, p)}
}

func (_c *MockStorer_Delete_Call) Run(run func(ctx context.Context, p permission.Permission)) *MockStorer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 permission.Permission
		if args[1] != nil {
			arg1 = args[1].(permission.Permission)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Delete_Call) Return(err error) *MockStorer_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Delete_Call) RunAndReturn(run func(ctx context.Context, p permission.Permission) error) *MockStorer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockStorer
func (_mock *MockStorer) Query(ctx context.Context, filter permission.QueryFilter, orderBy order.By, cur cursor.Cursor) ([]permission.Permission, error) {
	ret := _mock.Called(ctx, filter, orderBy, cur)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []permission.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, permission.QueryFilter, order.By, cursor.Cursor) ([]permission.Permission, error)); ok {
		return returnFunc(ctx, filter, orderBy, cur)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, permission.QueryFilter, order.By, cursor.Cursor) []permission.Permission); ok {
		r0 = returnFunc(ctx, filter, orderBy, cur)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, permission.QueryFilter, order.By, cursor.Cursor) error); ok {
		r1 = returnFunc(ctx, filter, orderBy, cur)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockStorer_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - filter permission.QueryFilter
//   - orderBy order.By
//   - cur cursor.Cursor
func (_e *MockStorer_Expecter) Query(ctx interface{}, filter interface{}, orderBy interface{}, cur interface{}) *MockStorer_Query_Call {
	return &MockStorer_Query_Call{Call: _e.mock.On("Query", ctx, filter, orderBy, cur)}
}

func (_c *MockStorer_Query_Call) Run(run func(ctx context.Context, filter permission.QueryFilter, orderBy order.By, cur cursor.Cursor)) *MockStorer_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 permission.QueryFilter
		if args[1] != nil {
			arg1 = args[1].(permission.QueryFilter)
		}
		var arg2 order.By
		if args[2] != nil {
			arg2 = args[2].(order.By)
		}
		var arg3 cursor.Cursor
		if args[3] != nil {
			arg3 = args[3].(cursor.Cursor)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorer_Query_Call) Return(permissions []permission.Permission, err error) *MockStorer_Query_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *MockStorer_Query_Call) RunAndReturn(run func(ctx context.Context, filter permission.QueryFilter, orderBy order.By, cur cursor.Cursor) ([]permission.Permission, error)) *MockStorer_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryByID provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryByID(ctx context.Context, permissionID uuid.UUID) (permission.Permission, error) {
	ret := _mock.Called(ctx, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for QueryByID")
	}

	var r0 permission.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (permission.Permission, error)); ok {
		return returnFunc(ctx, permissionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) permission.Permission); ok {
		r0 = returnFunc(ctx, permissionID)
	} else {
		r0 = ret.Get(0).(permission.Permission)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, permissionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryByID'
type MockStorer_QueryByID_Call struct {
	*mock.Call
}

// QueryByID is a helper method to define mock.On call
//   - ctx context.Context
//   - permissionID uuid.UUID
func (_e *MockStorer_Expecter) QueryByID(ctx interface{}, permissionID interface{}) *MockStorer_QueryByID_Call {
	return &MockStorer_QueryByID_Call{Call: _e.mock.On("QueryByID", ctx, permissionID)}
}

func (_c *MockStorer_QueryByID_Call) Run(run func(ctx context.Context, permissionID uuid.UUID)) *MockStorer_QueryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_QueryByID_Call) Return(permission1 permission.Permission, err error) *MockStorer_QueryByID_Call {
	_c.Call.Return(permission1, err)
	return _c
}

func (_c *MockStorer_QueryByID_Call) RunAndReturn(run func(ctx context.Context, permissionID uuid.UUID) (permission.Permission, error)) *MockStorer_QueryByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStorer
func (_mock *MockStorer) Update(ctx context.Context, p permission.Permission) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, permission.Permission) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStorer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p permission.Permission
func (_e *MockStorer_Expecter) Update(ctx interface{}, p interface{}) *MockStorer_Update_Call {
	return &MockStorer_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockStorer_Update_Call) Run(run func(ctx context.Context, p permission.Permission)) *MockStorer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 permission.Permission
		if args[1] != nil {
			arg1 = args[1].(permission.Permission)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Update_Call) Return(err error) *MockStorer_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Update_Call) RunAndReturn(run func(ctx context.Context, p permission.Permission) error) *MockStorer_Update_Call {
	_c.Call.Return(run)
	return _c
}
