// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package subscription_discount

import (
	"context"

	"github.com/Housiadas/cerberus/pkg/cursor"
	"github.com/Housiadas/cerberus/pkg/order"
	"github.com/Housiadas/cerberus/pkg/pgsql"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockStorer
func (_mock *MockStorer) Create(ctx context.Context, sd SubscriptionDiscount) error {
	ret := _mock.Called(ctx, sd)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SubscriptionDiscount) error); ok {
		r0 = returnFunc(ctx, sd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sd SubscriptionDiscount
func (_e *MockStorer_Expecter) Create(ctx interface{}, sd interface{}) *MockStorer_Create_Call {
	return &MockStorer_Create_Call{Call: _e.mock.On("Create", ctx, sd)}
}

func (_c *MockStorer_Create_Call) Run(run func(ctx context.Context, sd SubscriptionDiscount)) *MockStorer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SubscriptionDiscount
		if args[1] != nil {
			arg1 = args[1].(SubscriptionDiscount)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Create_Call) Return(err error) *MockStorer_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Create_Call) RunAndReturn(run func(ctx context.Context, sd SubscriptionDiscount) error) *MockStorer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewWithTx provides a mock function for the type MockStorer
func (_mock *MockStorer) NewWithTx(tx pgsql.CommitRollbacker) (Storer, error) {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for NewWithTx")
	}

	var r0 Storer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgsql.CommitRollbacker) (Storer, error)); ok {
		return returnFunc(tx)
	}
	if returnFunc, ok := ret.Get(0).(func(pgsql.CommitRollbacker) Storer); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Storer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgsql.CommitRollbacker) error); ok {
		r1 = returnFunc(tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_NewWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewWithTx'
type MockStorer_NewWithTx_Call struct {
	*mock.Call
}

// NewWithTx is a helper method to define mock.On call
//   - tx pgsql.CommitRollbacker
func (_e *MockStorer_Expecter) NewWithTx(tx interface{}) *MockStorer_NewWithTx_Call {
	return &MockStorer_NewWithTx_Call{Call: _e.mock.On("NewWithTx", tx)}
}

func (_c *MockStorer_NewWithTx_Call) Run(run func(tx pgsql.CommitRollbacker)) *MockStorer_NewWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgsql.CommitRollbacker
		if args[0] != nil {
			arg0 = args[0].(pgsql.CommitRollbacker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorer_NewWithTx_Call) Return(storer Storer, err error) *MockStorer_NewWithTx_Call {
	_c.Call.Return(storer, err)
	return _c
}

func (_c *MockStorer_NewWithTx_Call) RunAndReturn(run func(tx pgsql.CommitRollbacker) (Storer, error)) *MockStorer_NewWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockStorer
func (_mock *MockStorer) Query(ctx context.Context, filter QueryFilter, orderBy order.By, cur cursor.Cursor) ([]SubscriptionDiscount, error) {
	ret := _mock.Called(ctx, filter, orderBy, cur)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []SubscriptionDiscount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, QueryFilter, order.By, cursor.Cursor) ([]SubscriptionDiscount, error)); ok {
		return returnFunc(ctx, filter, orderBy, cur)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, QueryFilter, order.By, cursor.Cursor) []SubscriptionDiscount); ok {
		r0 = returnFunc(ctx, filter, orderBy, cur)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SubscriptionDiscount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, QueryFilter, order.By, cursor.Cursor) error); ok {
		r1 = returnFunc(ctx, filter, orderBy, cur)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockStorer_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - filter QueryFilter
//   - orderBy order.By
//   - cur cursor.Cursor
func (_e *MockStorer_Expecter) Query(ctx interface{}, filter interface{}, orderBy interface{}, cur interface{}) *MockStorer_Query_Call {
	return &MockStorer_Query_Call{Call: _e.mock.On("Query", ctx, filter, orderBy, cur)}
}

func (_c *MockStorer_Query_Call) Run(run func(ctx context.Context, filter QueryFilter, orderBy order.By, cur cursor.Cursor)) *MockStorer_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 QueryFilter
		if args[1] != nil {
			arg1 = args[1].(QueryFilter)
		}
		var arg2 order.By
		if args[2] != nil {
			arg2 = args[2].(order.By)
		}
		var arg3 cursor.Cursor
		if args[3] != nil {
			arg3 = args[3].(cursor.Cursor)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorer_Query_Call) Return(subscriptionDiscounts []SubscriptionDiscount, err error) *MockStorer_Query_Call {
	_c.Call.Return(subscriptionDiscounts, err)
	return _c
}

func (_c *MockStorer_Query_Call) RunAndReturn(run func(ctx context.Context, filter QueryFilter, orderBy order.By, cur cursor.Cursor) ([]SubscriptionDiscount, error)) *MockStorer_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryByID provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryByID(ctx context.Context, subscriptionDiscountID uuid.UUID) (SubscriptionDiscount, error) {
	ret := _mock.Called(ctx, subscriptionDiscountID)

	if len(ret) == 0 {
		panic("no return value specified for QueryByID")
	}

	var r0 SubscriptionDiscount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (SubscriptionDiscount, error)); ok {
		return returnFunc(ctx, subscriptionDiscountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) SubscriptionDiscount); ok {
		r0 = returnFunc(ctx, subscriptionDiscountID)
	} else {
		r0 = ret.Get(0).(SubscriptionDiscount)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, subscriptionDiscountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryByID'
type MockStorer_QueryByID_Call struct {
	*mock.Call
}

// QueryByID is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionDiscountID uuid.UUID
func (_e *MockStorer_Expecter) QueryByID(ctx interface{}, subscriptionDiscountID interface{}) *MockStorer_QueryByID_Call {
	return &MockStorer_QueryByID_Call{Call: _e.mock.On("QueryByID", ctx, subscriptionDiscountID)}
}

func (_c *MockStorer_QueryByID_Call) Run(run func(ctx context.Context, subscriptionDiscountID uuid.UUID)) *MockStorer_QueryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_QueryByID_Call) Return(subscriptionDiscount SubscriptionDiscount, err error) *MockStorer_QueryByID_Call {
	_c.Call.Return(subscriptionDiscount, err)
	return _c
}

func (_c *MockStorer_QueryByID_Call) RunAndReturn(run func(ctx context.Context, subscriptionDiscountID uuid.UUID) (SubscriptionDiscount, error)) *MockStorer_QueryByID_Call {
	_c.Call.Return(run)
	return _c
}

// QueryBySubscriptionID provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryBySubscriptionID(ctx context.Context, subscriptionID uuid.UUID) ([]SubscriptionDiscount, error) {
	ret := _mock.Called(ctx, subscriptionID)

	if len(ret) == 0 {
		panic("no return value specified for QueryBySubscriptionID")
	}

	var r0 []SubscriptionDiscount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]SubscriptionDiscount, error)); ok {
		return returnFunc(ctx, subscriptionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []SubscriptionDiscount); ok {
		r0 = returnFunc(ctx, subscriptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SubscriptionDiscount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, subscriptionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryBySubscriptionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryBySubscriptionID'
type MockStorer_QueryBySubscriptionID_Call struct {
	*mock.Call
}

// QueryBySubscriptionID is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriptionID uuid.UUID
func (_e *MockStorer_Expecter) QueryBySubscriptionID(ctx interface{}, subscriptionID interface{}) *MockStorer_QueryBySubscriptionID_Call {
	return &MockStorer_QueryBySubscriptionID_Call{Call: _e.mock.On("QueryBySubscriptionID", ctx, subscriptionID)}
}

func (_c *MockStorer_QueryBySubscriptionID_Call) Run(run func(ctx context.Context, subscriptionID uuid.UUID)) *MockStorer_QueryBySubscriptionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_QueryBySubscriptionID_Call) Return(subscriptionDiscounts []SubscriptionDiscount, err error) *MockStorer_QueryBySubscriptionID_Call {
	_c.Call.Return(subscriptionDiscounts, err)
	return _c
}

func (_c *MockStorer_QueryBySubscriptionID_Call) RunAndReturn(run func(ctx context.Context, subscriptionID uuid.UUID) ([]SubscriptionDiscount, error)) *MockStorer_QueryBySubscriptionID_Call {
	_c.Call.Return(run)
	return _c
}
