// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package outbox_test

import (
	"context"
	"time"

	"github.com/Housiadas/cerberus/db/sqlc"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// newMockgenerator creates a new instance of mockgenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockgenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockgenerator {
	mock := &mockgenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockgenerator is an autogenerated mock type for the generator type
type mockgenerator struct {
	mock.Mock
}

type mockgenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockgenerator) EXPECT() *mockgenerator_Expecter {
	return &mockgenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type mockgenerator
func (_mock *mockgenerator) Generate() (uuid.UUID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uuid.UUID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockgenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type mockgenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *mockgenerator_Expecter) Generate() *mockgenerator_Generate_Call {
	return &mockgenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *mockgenerator_Generate_Call) Run(run func()) *mockgenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockgenerator_Generate_Call) Return(uUID uuid.UUID, err error) *mockgenerator_Generate_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *mockgenerator_Generate_Call) RunAndReturn(run func() (uuid.UUID, error)) *mockgenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockclock creates a new instance of mockclock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockclock(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockclock {
	mock := &mockclock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockclock is an autogenerated mock type for the clock type
type mockclock struct {
	mock.Mock
}

type mockclock_Expecter struct {
	mock *mock.Mock
}

func (_m *mockclock) EXPECT() *mockclock_Expecter {
	return &mockclock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type mockclock
func (_mock *mockclock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// mockclock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type mockclock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *mockclock_Expecter) Now() *mockclock_Now_Call {
	return &mockclock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *mockclock_Now_Call) Run(run func()) *mockclock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockclock_Now_Call) Return(time1 time.Time) *mockclock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *mockclock_Now_Call) RunAndReturn(run func() time.Time) *mockclock_Now_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstorer creates a new instance of mockstorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstorer {
	mock := &mockstorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstorer is an autogenerated mock type for the storer type
type mockstorer struct {
	mock.Mock
}

type mockstorer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstorer) EXPECT() *mockstorer_Expecter {
	return &mockstorer_Expecter{mock: &_m.Mock}
}

// CreateOutbox provides a mock function for the type mockstorer
func (_mock *mockstorer) CreateOutbox(ctx context.Context, arg db.CreateOutboxParams) (db.Outbox, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateOutbox")
	}

	var r0 db.Outbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateOutboxParams) (db.Outbox, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateOutboxParams) db.Outbox); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Outbox)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateOutboxParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstorer_CreateOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOutbox'
type mockstorer_CreateOutbox_Call struct {
	*mock.Call
}

// CreateOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateOutboxParams
func (_e *mockstorer_Expecter) CreateOutbox(ctx interface{}, arg interface{}) *mockstorer_CreateOutbox_Call {
	return &mockstorer_CreateOutbox_Call{Call: _e.mock.On("CreateOutbox", ctx, arg)}
}

func (_c *mockstorer_CreateOutbox_Call) Run(run func(ctx context.Context, arg db.CreateOutboxParams)) *mockstorer_CreateOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateOutboxParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateOutboxParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_CreateOutbox_Call) Return(outbox db.Outbox, err error) *mockstorer_CreateOutbox_Call {
	_c.Call.Return(outbox, err)
	return _c
}

func (_c *mockstorer_CreateOutbox_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateOutboxParams) (db.Outbox, error)) *mockstorer_CreateOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnprocessedOutbox provides a mock function for the type mockstorer
func (_mock *mockstorer) GetUnprocessedOutbox(ctx context.Context, arg db.GetUnprocessedOutboxParams) ([]db.Outbox, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetUnprocessedOutbox")
	}

	var r0 []db.Outbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetUnprocessedOutboxParams) ([]db.Outbox, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.GetUnprocessedOutboxParams) []db.Outbox); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Outbox)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.GetUnprocessedOutboxParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstorer_GetUnprocessedOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnprocessedOutbox'
type mockstorer_GetUnprocessedOutbox_Call struct {
	*mock.Call
}

// GetUnprocessedOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetUnprocessedOutboxParams
func (_e *mockstorer_Expecter) GetUnprocessedOutbox(ctx interface{}, arg interface{}) *mockstorer_GetUnprocessedOutbox_Call {
	return &mockstorer_GetUnprocessedOutbox_Call{Call: _e.mock.On("GetUnprocessedOutbox", ctx, arg)}
}

func (_c *mockstorer_GetUnprocessedOutbox_Call) Run(run func(ctx context.Context, arg db.GetUnprocessedOutboxParams)) *mockstorer_GetUnprocessedOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.GetUnprocessedOutboxParams
		if args[1] != nil {
			arg1 = args[1].(db.GetUnprocessedOutboxParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_GetUnprocessedOutbox_Call) Return(outboxs []db.Outbox, err error) *mockstorer_GetUnprocessedOutbox_Call {
	_c.Call.Return(outboxs, err)
	return _c
}

func (_c *mockstorer_GetUnprocessedOutbox_Call) RunAndReturn(run func(ctx context.Context, arg db.GetUnprocessedOutboxParams) ([]db.Outbox, error)) *mockstorer_GetUnprocessedOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementRetryOutbox provides a mock function for the type mockstorer
func (_mock *mockstorer) IncrementRetryOutbox(ctx context.Context, ids uuid.UUID) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for IncrementRetryOutbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstorer_IncrementRetryOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementRetryOutbox'
type mockstorer_IncrementRetryOutbox_Call struct {
	*mock.Call
}

// IncrementRetryOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - ids uuid.UUID
func (_e *mockstorer_Expecter) IncrementRetryOutbox(ctx interface{}, ids interface{}) *mockstorer_IncrementRetryOutbox_Call {
	return &mockstorer_IncrementRetryOutbox_Call{Call: _e.mock.On("IncrementRetryOutbox", ctx, ids)}
}

func (_c *mockstorer_IncrementRetryOutbox_Call) Run(run func(ctx context.Context, ids uuid.UUID)) *mockstorer_IncrementRetryOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_IncrementRetryOutbox_Call) Return(err error) *mockstorer_IncrementRetryOutbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstorer_IncrementRetryOutbox_Call) RunAndReturn(run func(ctx context.Context, ids uuid.UUID) error) *mockstorer_IncrementRetryOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessedOutbox provides a mock function for the type mockstorer
func (_mock *mockstorer) MarkProcessedOutbox(ctx context.Context, arg db.MarkProcessedOutboxParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessedOutbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.MarkProcessedOutboxParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstorer_MarkProcessedOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessedOutbox'
type mockstorer_MarkProcessedOutbox_Call struct {
	*mock.Call
}

// MarkProcessedOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.MarkProcessedOutboxParams
func (_e *mockstorer_Expecter) MarkProcessedOutbox(ctx interface{}, arg interface{}) *mockstorer_MarkProcessedOutbox_Call {
	return &mockstorer_MarkProcessedOutbox_Call{Call: _e.mock.On("MarkProcessedOutbox", ctx, arg)}
}

func (_c *mockstorer_MarkProcessedOutbox_Call) Run(run func(ctx context.Context, arg db.MarkProcessedOutboxParams)) *mockstorer_MarkProcessedOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.MarkProcessedOutboxParams
		if args[1] != nil {
			arg1 = args[1].(db.MarkProcessedOutboxParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_MarkProcessedOutbox_Call) Return(err error) *mockstorer_MarkProcessedOutbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstorer_MarkProcessedOutbox_Call) RunAndReturn(run func(ctx context.Context, arg db.MarkProcessedOutboxParams) error) *mockstorer_MarkProcessedOutbox_Call {
	_c.Call.Return(run)
	return _c
}
