// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package outbox_test

import (
	"context"
	"time"

	"github.com/Housiadas/cerberus/internal/core/outbox"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockStorer
func (_mock *MockStorer) Create(ctx context.Context, o outbox.Outbox) error {
	ret := _mock.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbox.Outbox) error); ok {
		r0 = returnFunc(ctx, o)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - o outbox.Outbox
func (_e *MockStorer_Expecter) Create(ctx interface{}, o interface{}) *MockStorer_Create_Call {
	return &MockStorer_Create_Call{Call: _e.mock.On("Create", ctx, o)}
}

func (_c *MockStorer_Create_Call) Run(run func(ctx context.Context, o outbox.Outbox)) *MockStorer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbox.Outbox
		if args[1] != nil {
			arg1 = args[1].(outbox.Outbox)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Create_Call) Return(err error) *MockStorer_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Create_Call) RunAndReturn(run func(ctx context.Context, o outbox.Outbox) error) *MockStorer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementRetryCount provides a mock function for the type MockStorer
func (_mock *MockStorer) IncrementRetryCount(ctx context.Context, ids []uuid.UUID) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for IncrementRetryCount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_IncrementRetryCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementRetryCount'
type MockStorer_IncrementRetryCount_Call struct {
	*mock.Call
}

// IncrementRetryCount is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockStorer_Expecter) IncrementRetryCount(ctx interface{}, ids interface{}) *MockStorer_IncrementRetryCount_Call {
	return &MockStorer_IncrementRetryCount_Call{Call: _e.mock.On("IncrementRetryCount", ctx, ids)}
}

func (_c *MockStorer_IncrementRetryCount_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockStorer_IncrementRetryCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_IncrementRetryCount_Call) Return(err error) *MockStorer_IncrementRetryCount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_IncrementRetryCount_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) error) *MockStorer_IncrementRetryCount_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessed provides a mock function for the type MockStorer
func (_mock *MockStorer) MarkProcessed(ctx context.Context, ids []uuid.UUID, processedAt time.Time) error {
	ret := _mock.Called(ctx, ids, processedAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, ids, processedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_MarkProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessed'
type MockStorer_MarkProcessed_Call struct {
	*mock.Call
}

// MarkProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
//   - processedAt time.Time
func (_e *MockStorer_Expecter) MarkProcessed(ctx interface{}, ids interface{}, processedAt interface{}) *MockStorer_MarkProcessed_Call {
	return &MockStorer_MarkProcessed_Call{Call: _e.mock.On("MarkProcessed", ctx, ids, processedAt)}
}

func (_c *MockStorer_MarkProcessed_Call) Run(run func(ctx context.Context, ids []uuid.UUID, processedAt time.Time)) *MockStorer_MarkProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorer_MarkProcessed_Call) Return(err error) *MockStorer_MarkProcessed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_MarkProcessed_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID, processedAt time.Time) error) *MockStorer_MarkProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// QueryUnprocessed provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryUnprocessed(ctx context.Context, limit int, maxRetries int) ([]outbox.Outbox, error) {
	ret := _mock.Called(ctx, limit, maxRetries)

	if len(ret) == 0 {
		panic("no return value specified for QueryUnprocessed")
	}

	var r0 []outbox.Outbox
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]outbox.Outbox, error)); ok {
		return returnFunc(ctx, limit, maxRetries)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []outbox.Outbox); ok {
		r0 = returnFunc(ctx, limit, maxRetries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]outbox.Outbox)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, maxRetries)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryUnprocessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryUnprocessed'
type MockStorer_QueryUnprocessed_Call struct {
	*mock.Call
}

// QueryUnprocessed is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - maxRetries int
func (_e *MockStorer_Expecter) QueryUnprocessed(ctx interface{}, limit interface{}, maxRetries interface{}) *MockStorer_QueryUnprocessed_Call {
	return &MockStorer_QueryUnprocessed_Call{Call: _e.mock.On("QueryUnprocessed", ctx, limit, maxRetries)}
}

func (_c *MockStorer_QueryUnprocessed_Call) Run(run func(ctx context.Context, limit int, maxRetries int)) *MockStorer_QueryUnprocessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorer_QueryUnprocessed_Call) Return(outboxs []outbox.Outbox, err error) *MockStorer_QueryUnprocessed_Call {
	_c.Call.Return(outboxs, err)
	return _c
}

func (_c *MockStorer_QueryUnprocessed_Call) RunAndReturn(run func(ctx context.Context, limit int, maxRetries int) ([]outbox.Outbox, error)) *MockStorer_QueryUnprocessed_Call {
	_c.Call.Return(run)
	return _c
}

// newMockgenerator creates a new instance of mockgenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockgenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockgenerator {
	mock := &mockgenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockgenerator is an autogenerated mock type for the generator type
type mockgenerator struct {
	mock.Mock
}

type mockgenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockgenerator) EXPECT() *mockgenerator_Expecter {
	return &mockgenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type mockgenerator
func (_mock *mockgenerator) Generate() (uuid.UUID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uuid.UUID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockgenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type mockgenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *mockgenerator_Expecter) Generate() *mockgenerator_Generate_Call {
	return &mockgenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *mockgenerator_Generate_Call) Run(run func()) *mockgenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockgenerator_Generate_Call) Return(uUID uuid.UUID, err error) *mockgenerator_Generate_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *mockgenerator_Generate_Call) RunAndReturn(run func() (uuid.UUID, error)) *mockgenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockclock creates a new instance of mockclock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockclock(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockclock {
	mock := &mockclock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockclock is an autogenerated mock type for the clock type
type mockclock struct {
	mock.Mock
}

type mockclock_Expecter struct {
	mock *mock.Mock
}

func (_m *mockclock) EXPECT() *mockclock_Expecter {
	return &mockclock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type mockclock
func (_mock *mockclock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// mockclock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type mockclock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *mockclock_Expecter) Now() *mockclock_Now_Call {
	return &mockclock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *mockclock_Now_Call) Run(run func()) *mockclock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockclock_Now_Call) Return(time1 time.Time) *mockclock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *mockclock_Now_Call) RunAndReturn(run func() time.Time) *mockclock_Now_Call {
	_c.Call.Return(run)
	return _c
}

// newMocklogger creates a new instance of mocklogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocklogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocklogger {
	mock := &mocklogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocklogger is an autogenerated mock type for the logger type
type mocklogger struct {
	mock.Mock
}

type mocklogger_Expecter struct {
	mock *mock.Mock
}

func (_m *mocklogger) EXPECT() *mocklogger_Expecter {
	return &mocklogger_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type mocklogger
func (_mock *mocklogger) Error(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type mocklogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Error(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Error_Call {
	return &mocklogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Error_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Error_Call) Return() *mocklogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Error_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type mocklogger
func (_mock *mocklogger) Info(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type mocklogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Info(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Info_Call {
	return &mocklogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Info_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Info_Call) Return() *mocklogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Info_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Info_Call {
	_c.Run(run)
	return _c
}
