// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package billing_address_test

import (
	"context"

	"github.com/Housiadas/cerberus/internal/core/billing_address"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockStorer
func (_mock *MockStorer) Create(ctx context.Context, addr billing_address.BillingAddress) error {
	ret := _mock.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing_address.BillingAddress) error); ok {
		r0 = returnFunc(ctx, addr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - addr billing_address.BillingAddress
func (_e *MockStorer_Expecter) Create(ctx interface{}, addr interface{}) *MockStorer_Create_Call {
	return &MockStorer_Create_Call{Call: _e.mock.On("Create", ctx, addr)}
}

func (_c *MockStorer_Create_Call) Run(run func(ctx context.Context, addr billing_address.BillingAddress)) *MockStorer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing_address.BillingAddress
		if args[1] != nil {
			arg1 = args[1].(billing_address.BillingAddress)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Create_Call) Return(err error) *MockStorer_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Create_Call) RunAndReturn(run func(ctx context.Context, addr billing_address.BillingAddress) error) *MockStorer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockStorer
func (_mock *MockStorer) Delete(ctx context.Context, addr billing_address.BillingAddress) error {
	ret := _mock.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing_address.BillingAddress) error); ok {
		r0 = returnFunc(ctx, addr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - addr billing_address.BillingAddress
func (_e *MockStorer_Expecter) Delete(ctx interface{}, addr interface{}) *MockStorer_Delete_Call {
	return &MockStorer_Delete_Call{Call: _e.mock.On("Delete", ctx, addr)}
}

func (_c *MockStorer_Delete_Call) Run(run func(ctx context.Context, addr billing_address.BillingAddress)) *MockStorer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing_address.BillingAddress
		if args[1] != nil {
			arg1 = args[1].(billing_address.BillingAddress)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Delete_Call) Return(err error) *MockStorer_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Delete_Call) RunAndReturn(run func(ctx context.Context, addr billing_address.BillingAddress) error) *MockStorer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// QueryByAccountID provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryByAccountID(ctx context.Context, accountID uuid.UUID) ([]billing_address.BillingAddress, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for QueryByAccountID")
	}

	var r0 []billing_address.BillingAddress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]billing_address.BillingAddress, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []billing_address.BillingAddress); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]billing_address.BillingAddress)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryByAccountID'
type MockStorer_QueryByAccountID_Call struct {
	*mock.Call
}

// QueryByAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
func (_e *MockStorer_Expecter) QueryByAccountID(ctx interface{}, accountID interface{}) *MockStorer_QueryByAccountID_Call {
	return &MockStorer_QueryByAccountID_Call{Call: _e.mock.On("QueryByAccountID", ctx, accountID)}
}

func (_c *MockStorer_QueryByAccountID_Call) Run(run func(ctx context.Context, accountID uuid.UUID)) *MockStorer_QueryByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_QueryByAccountID_Call) Return(billingAddresss []billing_address.BillingAddress, err error) *MockStorer_QueryByAccountID_Call {
	_c.Call.Return(billingAddresss, err)
	return _c
}

func (_c *MockStorer_QueryByAccountID_Call) RunAndReturn(run func(ctx context.Context, accountID uuid.UUID) ([]billing_address.BillingAddress, error)) *MockStorer_QueryByAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// QueryByID provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryByID(ctx context.Context, id uuid.UUID) (billing_address.BillingAddress, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for QueryByID")
	}

	var r0 billing_address.BillingAddress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (billing_address.BillingAddress, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) billing_address.BillingAddress); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(billing_address.BillingAddress)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryByID'
type MockStorer_QueryByID_Call struct {
	*mock.Call
}

// QueryByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockStorer_Expecter) QueryByID(ctx interface{}, id interface{}) *MockStorer_QueryByID_Call {
	return &MockStorer_QueryByID_Call{Call: _e.mock.On("QueryByID", ctx, id)}
}

func (_c *MockStorer_QueryByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStorer_QueryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_QueryByID_Call) Return(billingAddress billing_address.BillingAddress, err error) *MockStorer_QueryByID_Call {
	_c.Call.Return(billingAddress, err)
	return _c
}

func (_c *MockStorer_QueryByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (billing_address.BillingAddress, error)) *MockStorer_QueryByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStorer
func (_mock *MockStorer) Update(ctx context.Context, addr billing_address.BillingAddress) error {
	ret := _mock.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, billing_address.BillingAddress) error); ok {
		r0 = returnFunc(ctx, addr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStorer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - addr billing_address.BillingAddress
func (_e *MockStorer_Expecter) Update(ctx interface{}, addr interface{}) *MockStorer_Update_Call {
	return &MockStorer_Update_Call{Call: _e.mock.On("Update", ctx, addr)}
}

func (_c *MockStorer_Update_Call) Run(run func(ctx context.Context, addr billing_address.BillingAddress)) *MockStorer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 billing_address.BillingAddress
		if args[1] != nil {
			arg1 = args[1].(billing_address.BillingAddress)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Update_Call) Return(err error) *MockStorer_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Update_Call) RunAndReturn(run func(ctx context.Context, addr billing_address.BillingAddress) error) *MockStorer_Update_Call {
	_c.Call.Return(run)
	return _c
}
