// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package permission_test

import (
	"context"

	"github.com/Housiadas/cerberus/internal/core/permission"
	"github.com/Housiadas/cerberus/pkg/cursor"
	"github.com/Housiadas/cerberus/pkg/order"
	"github.com/Housiadas/cerberus/pkg/pgsql"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockStorer
func (_mock *MockStorer) Create(ctx context.Context, p permission.Permission) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, permission.Permission) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p permission.Permission
func (_e *MockStorer_Expecter) Create(ctx interface{}, p interface{}) *MockStorer_Create_Call {
	return &MockStorer_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockStorer_Create_Call) Run(run func(ctx context.Context, p permission.Permission)) *MockStorer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 permission.Permission
		if args[1] != nil {
			arg1 = args[1].(permission.Permission)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Create_Call) Return(err error) *MockStorer_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Create_Call) RunAndReturn(run func(ctx context.Context, p permission.Permission) error) *MockStorer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockStorer
func (_mock *MockStorer) Delete(ctx context.Context, p permission.Permission) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, permission.Permission) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - p permission.Permission
func (_e *MockStorer_Expecter) Delete(ctx interface{}, p interface{}) *MockStorer_Delete_Call {
	return &MockStorer_Delete_Call{Call: _e.mock.On("Delete", ctx, p)}
}

func (_c *MockStorer_Delete_Call) Run(run func(ctx context.Context, p permission.Permission)) *MockStorer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 permission.Permission
		if args[1] != nil {
			arg1 = args[1].(permission.Permission)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Delete_Call) Return(err error) *MockStorer_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Delete_Call) RunAndReturn(run func(ctx context.Context, p permission.Permission) error) *MockStorer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewWithTx provides a mock function for the type MockStorer
func (_mock *MockStorer) NewWithTx(tx pgsql.CommitRollbacker) (permission.Storer, error) {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for NewWithTx")
	}

	var r0 permission.Storer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgsql.CommitRollbacker) (permission.Storer, error)); ok {
		return returnFunc(tx)
	}
	if returnFunc, ok := ret.Get(0).(func(pgsql.CommitRollbacker) permission.Storer); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(permission.Storer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgsql.CommitRollbacker) error); ok {
		r1 = returnFunc(tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_NewWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewWithTx'
type MockStorer_NewWithTx_Call struct {
	*mock.Call
}

// NewWithTx is a helper method to define mock.On call
//   - tx pgsql.CommitRollbacker
func (_e *MockStorer_Expecter) NewWithTx(tx interface{}) *MockStorer_NewWithTx_Call {
	return &MockStorer_NewWithTx_Call{Call: _e.mock.On("NewWithTx", tx)}
}

func (_c *MockStorer_NewWithTx_Call) Run(run func(tx pgsql.CommitRollbacker)) *MockStorer_NewWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgsql.CommitRollbacker
		if args[0] != nil {
			arg0 = args[0].(pgsql.CommitRollbacker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorer_NewWithTx_Call) Return(storer permission.Storer, err error) *MockStorer_NewWithTx_Call {
	_c.Call.Return(storer, err)
	return _c
}

func (_c *MockStorer_NewWithTx_Call) RunAndReturn(run func(tx pgsql.CommitRollbacker) (permission.Storer, error)) *MockStorer_NewWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockStorer
func (_mock *MockStorer) Query(ctx context.Context, filter permission.QueryFilter, orderBy order.By, cur cursor.Cursor) ([]permission.Permission, error) {
	ret := _mock.Called(ctx, filter, orderBy, cur)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []permission.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, permission.QueryFilter, order.By, cursor.Cursor) ([]permission.Permission, error)); ok {
		return returnFunc(ctx, filter, orderBy, cur)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, permission.QueryFilter, order.By, cursor.Cursor) []permission.Permission); ok {
		r0 = returnFunc(ctx, filter, orderBy, cur)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, permission.QueryFilter, order.By, cursor.Cursor) error); ok {
		r1 = returnFunc(ctx, filter, orderBy, cur)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockStorer_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - filter permission.QueryFilter
//   - orderBy order.By
//   - cur cursor.Cursor
func (_e *MockStorer_Expecter) Query(ctx interface{}, filter interface{}, orderBy interface{}, cur interface{}) *MockStorer_Query_Call {
	return &MockStorer_Query_Call{Call: _e.mock.On("Query", ctx, filter, orderBy, cur)}
}

func (_c *MockStorer_Query_Call) Run(run func(ctx context.Context, filter permission.QueryFilter, orderBy order.By, cur cursor.Cursor)) *MockStorer_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 permission.QueryFilter
		if args[1] != nil {
			arg1 = args[1].(permission.QueryFilter)
		}
		var arg2 order.By
		if args[2] != nil {
			arg2 = args[2].(order.By)
		}
		var arg3 cursor.Cursor
		if args[3] != nil {
			arg3 = args[3].(cursor.Cursor)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorer_Query_Call) Return(permissions []permission.Permission, err error) *MockStorer_Query_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *MockStorer_Query_Call) RunAndReturn(run func(ctx context.Context, filter permission.QueryFilter, orderBy order.By, cur cursor.Cursor) ([]permission.Permission, error)) *MockStorer_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryByID provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryByID(ctx context.Context, permissionID uuid.UUID) (permission.Permission, error) {
	ret := _mock.Called(ctx, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for QueryByID")
	}

	var r0 permission.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (permission.Permission, error)); ok {
		return returnFunc(ctx, permissionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) permission.Permission); ok {
		r0 = returnFunc(ctx, permissionID)
	} else {
		r0 = ret.Get(0).(permission.Permission)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, permissionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryByID'
type MockStorer_QueryByID_Call struct {
	*mock.Call
}

// QueryByID is a helper method to define mock.On call
//   - ctx context.Context
//   - permissionID uuid.UUID
func (_e *MockStorer_Expecter) QueryByID(ctx interface{}, permissionID interface{}) *MockStorer_QueryByID_Call {
	return &MockStorer_QueryByID_Call{Call: _e.mock.On("QueryByID", ctx, permissionID)}
}

func (_c *MockStorer_QueryByID_Call) Run(run func(ctx context.Context, permissionID uuid.UUID)) *MockStorer_QueryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_QueryByID_Call) Return(permission1 permission.Permission, err error) *MockStorer_QueryByID_Call {
	_c.Call.Return(permission1, err)
	return _c
}

func (_c *MockStorer_QueryByID_Call) RunAndReturn(run func(ctx context.Context, permissionID uuid.UUID) (permission.Permission, error)) *MockStorer_QueryByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStorer
func (_mock *MockStorer) Update(ctx context.Context, p permission.Permission) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, permission.Permission) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStorer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p permission.Permission
func (_e *MockStorer_Expecter) Update(ctx interface{}, p interface{}) *MockStorer_Update_Call {
	return &MockStorer_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockStorer_Update_Call) Run(run func(ctx context.Context, p permission.Permission)) *MockStorer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 permission.Permission
		if args[1] != nil {
			arg1 = args[1].(permission.Permission)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Update_Call) Return(err error) *MockStorer_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Update_Call) RunAndReturn(run func(ctx context.Context, p permission.Permission) error) *MockStorer_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMocklogger creates a new instance of mocklogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocklogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocklogger {
	mock := &mocklogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocklogger is an autogenerated mock type for the logger type
type mocklogger struct {
	mock.Mock
}

type mocklogger_Expecter struct {
	mock *mock.Mock
}

func (_m *mocklogger) EXPECT() *mocklogger_Expecter {
	return &mocklogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type mocklogger
func (_mock *mocklogger) Debug(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type mocklogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Debug(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Debug_Call {
	return &mocklogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Debug_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Debug_Call) Return() *mocklogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Debug_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Debugc provides a mock function for the type mocklogger
func (_mock *mocklogger) Debugc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Debugc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugc'
type mocklogger_Debugc_Call struct {
	*mock.Call
}

// Debugc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Debugc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Debugc_Call {
	return &mocklogger_Debugc_Call{Call: _e.mock.On("Debugc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Debugc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Debugc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Debugc_Call) Return() *mocklogger_Debugc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Debugc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Debugc_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type mocklogger
func (_mock *mocklogger) Error(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type mocklogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Error(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Error_Call {
	return &mocklogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Error_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Error_Call) Return() *mocklogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Error_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Error_Call {
	_c.Run(run)
	return _c
}

// Errorc provides a mock function for the type mocklogger
func (_mock *mocklogger) Errorc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Errorc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorc'
type mocklogger_Errorc_Call struct {
	*mock.Call
}

// Errorc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Errorc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Errorc_Call {
	return &mocklogger_Errorc_Call{Call: _e.mock.On("Errorc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Errorc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Errorc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Errorc_Call) Return() *mocklogger_Errorc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Errorc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Errorc_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type mocklogger
func (_mock *mocklogger) Info(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type mocklogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Info(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Info_Call {
	return &mocklogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Info_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Info_Call) Return() *mocklogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Info_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Info_Call {
	_c.Run(run)
	return _c
}

// Infoc provides a mock function for the type mocklogger
func (_mock *mocklogger) Infoc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Infoc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infoc'
type mocklogger_Infoc_Call struct {
	*mock.Call
}

// Infoc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Infoc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Infoc_Call {
	return &mocklogger_Infoc_Call{Call: _e.mock.On("Infoc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Infoc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Infoc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Infoc_Call) Return() *mocklogger_Infoc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Infoc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Infoc_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type mocklogger
func (_mock *mocklogger) Warn(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type mocklogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Warn(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Warn_Call {
	return &mocklogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Warn_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Warn_Call) Return() *mocklogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Warn_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Warn_Call {
	_c.Run(run)
	return _c
}

// Warnc provides a mock function for the type mocklogger
func (_mock *mocklogger) Warnc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Warnc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warnc'
type mocklogger_Warnc_Call struct {
	*mock.Call
}

// Warnc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Warnc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Warnc_Call {
	return &mocklogger_Warnc_Call{Call: _e.mock.On("Warnc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Warnc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Warnc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Warnc_Call) Return() *mocklogger_Warnc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Warnc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Warnc_Call {
	_c.Run(run)
	return _c
}

// newMockgenerator creates a new instance of mockgenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockgenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockgenerator {
	mock := &mockgenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockgenerator is an autogenerated mock type for the generator type
type mockgenerator struct {
	mock.Mock
}

type mockgenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockgenerator) EXPECT() *mockgenerator_Expecter {
	return &mockgenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type mockgenerator
func (_mock *mockgenerator) Generate() (uuid.UUID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uuid.UUID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockgenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type mockgenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *mockgenerator_Expecter) Generate() *mockgenerator_Generate_Call {
	return &mockgenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *mockgenerator_Generate_Call) Run(run func()) *mockgenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockgenerator_Generate_Call) Return(uUID uuid.UUID, err error) *mockgenerator_Generate_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *mockgenerator_Generate_Call) RunAndReturn(run func() (uuid.UUID, error)) *mockgenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}
