apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-outbox-cleanup
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "app.labels" . | nindent 4 }}
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        {{ include "app.selectorLabels" . | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            {{ include "app.selectorLabels" . | nindent 12 }}
        spec:
          containers:
            - name: outbox-cleanup
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["./cerberus-cron", "outbox-cleanup"]
              volumeMounts:
                - name: config
                  mountPath: /app/config.yaml
                  subPath: config.yaml
          restartPolicy: OnFailure
          volumes:
            - name: config
              configMap:
                name: {{ include "app.fullname" . }}-config
