apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
      protocol: TCP
      name: http-api
    - port: {{ .Values.service.debugPort }}
      targetPort: {{ .Values.service.debugPort }}
      protocol: TCP
      name: http-debug
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
