// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package subscription

import (
	"context"

	"github.com/Housiadas/cerberus/pkg/pgsql"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockStorer
func (_mock *MockStorer) Create(ctx context.Context, sub Subscription) error {
	ret := _mock.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Subscription) error); ok {
		r0 = returnFunc(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sub Subscription
func (_e *MockStorer_Expecter) Create(ctx interface{}, sub interface{}) *MockStorer_Create_Call {
	return &MockStorer_Create_Call{Call: _e.mock.On("Create", ctx, sub)}
}

func (_c *MockStorer_Create_Call) Run(run func(ctx context.Context, sub Subscription)) *MockStorer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Subscription
		if args[1] != nil {
			arg1 = args[1].(Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Create_Call) Return(err error) *MockStorer_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Create_Call) RunAndReturn(run func(ctx context.Context, sub Subscription) error) *MockStorer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewWithTx provides a mock function for the type MockStorer
func (_mock *MockStorer) NewWithTx(tx pgsql.CommitRollbacker) (Storer, error) {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for NewWithTx")
	}

	var r0 Storer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pgsql.CommitRollbacker) (Storer, error)); ok {
		return returnFunc(tx)
	}
	if returnFunc, ok := ret.Get(0).(func(pgsql.CommitRollbacker) Storer); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Storer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pgsql.CommitRollbacker) error); ok {
		r1 = returnFunc(tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_NewWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewWithTx'
type MockStorer_NewWithTx_Call struct {
	*mock.Call
}

// NewWithTx is a helper method to define mock.On call
//   - tx pgsql.CommitRollbacker
func (_e *MockStorer_Expecter) NewWithTx(tx interface{}) *MockStorer_NewWithTx_Call {
	return &MockStorer_NewWithTx_Call{Call: _e.mock.On("NewWithTx", tx)}
}

func (_c *MockStorer_NewWithTx_Call) Run(run func(tx pgsql.CommitRollbacker)) *MockStorer_NewWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgsql.CommitRollbacker
		if args[0] != nil {
			arg0 = args[0].(pgsql.CommitRollbacker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorer_NewWithTx_Call) Return(storer Storer, err error) *MockStorer_NewWithTx_Call {
	_c.Call.Return(storer, err)
	return _c
}

func (_c *MockStorer_NewWithTx_Call) RunAndReturn(run func(tx pgsql.CommitRollbacker) (Storer, error)) *MockStorer_NewWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// QueryByAccountID provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryByAccountID(ctx context.Context, accountID uuid.UUID) ([]Subscription, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for QueryByAccountID")
	}

	var r0 []Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]Subscription, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []Subscription); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryByAccountID'
type MockStorer_QueryByAccountID_Call struct {
	*mock.Call
}

// QueryByAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
func (_e *MockStorer_Expecter) QueryByAccountID(ctx interface{}, accountID interface{}) *MockStorer_QueryByAccountID_Call {
	return &MockStorer_QueryByAccountID_Call{Call: _e.mock.On("QueryByAccountID", ctx, accountID)}
}

func (_c *MockStorer_QueryByAccountID_Call) Run(run func(ctx context.Context, accountID uuid.UUID)) *MockStorer_QueryByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_QueryByAccountID_Call) Return(subscriptions []Subscription, err error) *MockStorer_QueryByAccountID_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *MockStorer_QueryByAccountID_Call) RunAndReturn(run func(ctx context.Context, accountID uuid.UUID) ([]Subscription, error)) *MockStorer_QueryByAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// QueryByStripeID provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryByStripeID(ctx context.Context, stripeSubID string) (Subscription, error) {
	ret := _mock.Called(ctx, stripeSubID)

	if len(ret) == 0 {
		panic("no return value specified for QueryByStripeID")
	}

	var r0 Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (Subscription, error)); ok {
		return returnFunc(ctx, stripeSubID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) Subscription); ok {
		r0 = returnFunc(ctx, stripeSubID)
	} else {
		r0 = ret.Get(0).(Subscription)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, stripeSubID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryByStripeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryByStripeID'
type MockStorer_QueryByStripeID_Call struct {
	*mock.Call
}

// QueryByStripeID is a helper method to define mock.On call
//   - ctx context.Context
//   - stripeSubID string
func (_e *MockStorer_Expecter) QueryByStripeID(ctx interface{}, stripeSubID interface{}) *MockStorer_QueryByStripeID_Call {
	return &MockStorer_QueryByStripeID_Call{Call: _e.mock.On("QueryByStripeID", ctx, stripeSubID)}
}

func (_c *MockStorer_QueryByStripeID_Call) Run(run func(ctx context.Context, stripeSubID string)) *MockStorer_QueryByStripeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_QueryByStripeID_Call) Return(subscription Subscription, err error) *MockStorer_QueryByStripeID_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockStorer_QueryByStripeID_Call) RunAndReturn(run func(ctx context.Context, stripeSubID string) (Subscription, error)) *MockStorer_QueryByStripeID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStorer
func (_mock *MockStorer) Update(ctx context.Context, sub Subscription) error {
	ret := _mock.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Subscription) error); ok {
		r0 = returnFunc(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStorer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - sub Subscription
func (_e *MockStorer_Expecter) Update(ctx interface{}, sub interface{}) *MockStorer_Update_Call {
	return &MockStorer_Update_Call{Call: _e.mock.On("Update", ctx, sub)}
}

func (_c *MockStorer_Update_Call) Run(run func(ctx context.Context, sub Subscription)) *MockStorer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Subscription
		if args[1] != nil {
			arg1 = args[1].(Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Update_Call) Return(err error) *MockStorer_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Update_Call) RunAndReturn(run func(ctx context.Context, sub Subscription) error) *MockStorer_Update_Call {
	_c.Call.Return(run)
	return _c
}
