// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user_test

import (
	"context"
	"net/mail"
	"time"

	"github.com/Housiadas/cerberus/internal/core/user"
	"github.com/Housiadas/cerberus/internal/types/event"
	"github.com/Housiadas/cerberus/pkg/cursor"
	"github.com/Housiadas/cerberus/pkg/order"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockStorer
func (_mock *MockStorer) Create(ctx context.Context, usr user.User) error {
	ret := _mock.Called(ctx, usr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) error); ok {
		r0 = returnFunc(ctx, usr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - usr user.User
func (_e *MockStorer_Expecter) Create(ctx interface{}, usr interface{}) *MockStorer_Create_Call {
	return &MockStorer_Create_Call{Call: _e.mock.On("Create", ctx, usr)}
}

func (_c *MockStorer_Create_Call) Run(run func(ctx context.Context, usr user.User)) *MockStorer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.User
		if args[1] != nil {
			arg1 = args[1].(user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Create_Call) Return(err error) *MockStorer_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Create_Call) RunAndReturn(run func(ctx context.Context, usr user.User) error) *MockStorer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockStorer
func (_mock *MockStorer) Delete(ctx context.Context, usr user.User) error {
	ret := _mock.Called(ctx, usr)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) error); ok {
		r0 = returnFunc(ctx, usr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - usr user.User
func (_e *MockStorer_Expecter) Delete(ctx interface{}, usr interface{}) *MockStorer_Delete_Call {
	return &MockStorer_Delete_Call{Call: _e.mock.On("Delete", ctx, usr)}
}

func (_c *MockStorer_Delete_Call) Run(run func(ctx context.Context, usr user.User)) *MockStorer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.User
		if args[1] != nil {
			arg1 = args[1].(user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Delete_Call) Return(err error) *MockStorer_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Delete_Call) RunAndReturn(run func(ctx context.Context, usr user.User) error) *MockStorer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockStorer
func (_mock *MockStorer) Query(ctx context.Context, filter user.QueryFilter, orderBy order.By, cur cursor.Cursor) ([]user.User, error) {
	ret := _mock.Called(ctx, filter, orderBy, cur)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.QueryFilter, order.By, cursor.Cursor) ([]user.User, error)); ok {
		return returnFunc(ctx, filter, orderBy, cur)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.QueryFilter, order.By, cursor.Cursor) []user.User); ok {
		r0 = returnFunc(ctx, filter, orderBy, cur)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.QueryFilter, order.By, cursor.Cursor) error); ok {
		r1 = returnFunc(ctx, filter, orderBy, cur)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockStorer_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - filter user.QueryFilter
//   - orderBy order.By
//   - cur cursor.Cursor
func (_e *MockStorer_Expecter) Query(ctx interface{}, filter interface{}, orderBy interface{}, cur interface{}) *MockStorer_Query_Call {
	return &MockStorer_Query_Call{Call: _e.mock.On("Query", ctx, filter, orderBy, cur)}
}

func (_c *MockStorer_Query_Call) Run(run func(ctx context.Context, filter user.QueryFilter, orderBy order.By, cur cursor.Cursor)) *MockStorer_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.QueryFilter
		if args[1] != nil {
			arg1 = args[1].(user.QueryFilter)
		}
		var arg2 order.By
		if args[2] != nil {
			arg2 = args[2].(order.By)
		}
		var arg3 cursor.Cursor
		if args[3] != nil {
			arg3 = args[3].(cursor.Cursor)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorer_Query_Call) Return(users []user.User, err error) *MockStorer_Query_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockStorer_Query_Call) RunAndReturn(run func(ctx context.Context, filter user.QueryFilter, orderBy order.By, cur cursor.Cursor) ([]user.User, error)) *MockStorer_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryByEmail provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryByEmail(ctx context.Context, email mail.Address) (user.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for QueryByEmail")
	}

	var r0 user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mail.Address) (user.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mail.Address) user.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mail.Address) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryByEmail'
type MockStorer_QueryByEmail_Call struct {
	*mock.Call
}

// QueryByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email mail.Address
func (_e *MockStorer_Expecter) QueryByEmail(ctx interface{}, email interface{}) *MockStorer_QueryByEmail_Call {
	return &MockStorer_QueryByEmail_Call{Call: _e.mock.On("QueryByEmail", ctx, email)}
}

func (_c *MockStorer_QueryByEmail_Call) Run(run func(ctx context.Context, email mail.Address)) *MockStorer_QueryByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mail.Address
		if args[1] != nil {
			arg1 = args[1].(mail.Address)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_QueryByEmail_Call) Return(user1 user.User, err error) *MockStorer_QueryByEmail_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockStorer_QueryByEmail_Call) RunAndReturn(run func(ctx context.Context, email mail.Address) (user.User, error)) *MockStorer_QueryByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// QueryByID provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryByID(ctx context.Context, userID uuid.UUID) (user.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for QueryByID")
	}

	var r0 user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (user.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) user.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryByID'
type MockStorer_QueryByID_Call struct {
	*mock.Call
}

// QueryByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStorer_Expecter) QueryByID(ctx interface{}, userID interface{}) *MockStorer_QueryByID_Call {
	return &MockStorer_QueryByID_Call{Call: _e.mock.On("QueryByID", ctx, userID)}
}

func (_c *MockStorer_QueryByID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStorer_QueryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_QueryByID_Call) Return(user1 user.User, err error) *MockStorer_QueryByID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockStorer_QueryByID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (user.User, error)) *MockStorer_QueryByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStorer
func (_mock *MockStorer) Update(ctx context.Context, usr user.User) error {
	ret := _mock.Called(ctx, usr)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.User) error); ok {
		r0 = returnFunc(ctx, usr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStorer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - usr user.User
func (_e *MockStorer_Expecter) Update(ctx interface{}, usr interface{}) *MockStorer_Update_Call {
	return &MockStorer_Update_Call{Call: _e.mock.On("Update", ctx, usr)}
}

func (_c *MockStorer_Update_Call) Run(run func(ctx context.Context, usr user.User)) *MockStorer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.User
		if args[1] != nil {
			arg1 = args[1].(user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Update_Call) Return(err error) *MockStorer_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Update_Call) RunAndReturn(run func(ctx context.Context, usr user.User) error) *MockStorer_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMocklogger creates a new instance of mocklogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocklogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocklogger {
	mock := &mocklogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocklogger is an autogenerated mock type for the logger type
type mocklogger struct {
	mock.Mock
}

type mocklogger_Expecter struct {
	mock *mock.Mock
}

func (_m *mocklogger) EXPECT() *mocklogger_Expecter {
	return &mocklogger_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type mocklogger
func (_mock *mocklogger) Error(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type mocklogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Error(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Error_Call {
	return &mocklogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Error_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Error_Call) Return() *mocklogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Error_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Error_Call {
	_c.Run(run)
	return _c
}

// Errorc provides a mock function for the type mocklogger
func (_mock *mocklogger) Errorc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Errorc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorc'
type mocklogger_Errorc_Call struct {
	*mock.Call
}

// Errorc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Errorc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Errorc_Call {
	return &mocklogger_Errorc_Call{Call: _e.mock.On("Errorc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Errorc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Errorc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Errorc_Call) Return() *mocklogger_Errorc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Errorc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Errorc_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type mocklogger
func (_mock *mocklogger) Info(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type mocklogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Info(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Info_Call {
	return &mocklogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Info_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Info_Call) Return() *mocklogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Info_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Info_Call {
	_c.Run(run)
	return _c
}

// Infoc provides a mock function for the type mocklogger
func (_mock *mocklogger) Infoc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Infoc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infoc'
type mocklogger_Infoc_Call struct {
	*mock.Call
}

// Infoc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Infoc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Infoc_Call {
	return &mocklogger_Infoc_Call{Call: _e.mock.On("Infoc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Infoc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Infoc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Infoc_Call) Return() *mocklogger_Infoc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Infoc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Infoc_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type mocklogger
func (_mock *mocklogger) Warn(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// mocklogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type mocklogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Warn(ctx interface{}, msg interface{}, args ...interface{}) *mocklogger_Warn_Call {
	return &mocklogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *mocklogger_Warn_Call) Run(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocklogger_Warn_Call) Return() *mocklogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Warn_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *mocklogger_Warn_Call {
	_c.Run(run)
	return _c
}

// Warnc provides a mock function for the type mocklogger
func (_mock *mocklogger) Warnc(ctx context.Context, caller int, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, caller, msg, args)
	} else {
		_mock.Called(ctx, caller, msg)
	}

	return
}

// mocklogger_Warnc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warnc'
type mocklogger_Warnc_Call struct {
	*mock.Call
}

// Warnc is a helper method to define mock.On call
//   - ctx context.Context
//   - caller int
//   - msg string
//   - args ...any
func (_e *mocklogger_Expecter) Warnc(ctx interface{}, caller interface{}, msg interface{}, args ...interface{}) *mocklogger_Warnc_Call {
	return &mocklogger_Warnc_Call{Call: _e.mock.On("Warnc",
		append([]interface{}{ctx, caller, msg}, args...)...)}
}

func (_c *mocklogger_Warnc_Call) Run(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Warnc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *mocklogger_Warnc_Call) Return() *mocklogger_Warnc_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocklogger_Warnc_Call) RunAndReturn(run func(ctx context.Context, caller int, msg string, args ...any)) *mocklogger_Warnc_Call {
	_c.Run(run)
	return _c
}

// newMockgenerator creates a new instance of mockgenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockgenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockgenerator {
	mock := &mockgenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockgenerator is an autogenerated mock type for the generator type
type mockgenerator struct {
	mock.Mock
}

type mockgenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockgenerator) EXPECT() *mockgenerator_Expecter {
	return &mockgenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type mockgenerator
func (_mock *mockgenerator) Generate() (uuid.UUID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uuid.UUID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockgenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type mockgenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *mockgenerator_Expecter) Generate() *mockgenerator_Generate_Call {
	return &mockgenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *mockgenerator_Generate_Call) Run(run func()) *mockgenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockgenerator_Generate_Call) Return(uUID uuid.UUID, err error) *mockgenerator_Generate_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *mockgenerator_Generate_Call) RunAndReturn(run func() (uuid.UUID, error)) *mockgenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockclock creates a new instance of mockclock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockclock(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockclock {
	mock := &mockclock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockclock is an autogenerated mock type for the clock type
type mockclock struct {
	mock.Mock
}

type mockclock_Expecter struct {
	mock *mock.Mock
}

func (_m *mockclock) EXPECT() *mockclock_Expecter {
	return &mockclock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type mockclock
func (_mock *mockclock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// mockclock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type mockclock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *mockclock_Expecter) Now() *mockclock_Now_Call {
	return &mockclock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *mockclock_Now_Call) Run(run func()) *mockclock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockclock_Now_Call) Return(time1 time.Time) *mockclock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *mockclock_Now_Call) RunAndReturn(run func() time.Time) *mockclock_Now_Call {
	_c.Call.Return(run)
	return _c
}

// newMockhasher creates a new instance of mockhasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockhasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockhasher {
	mock := &mockhasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockhasher is an autogenerated mock type for the hasher type
type mockhasher struct {
	mock.Mock
}

type mockhasher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockhasher) EXPECT() *mockhasher_Expecter {
	return &mockhasher_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type mockhasher
func (_mock *mockhasher) Compare(hashedPassword []byte, password string) error {
	ret := _mock.Called(hashedPassword, password)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, string) error); ok {
		r0 = returnFunc(hashedPassword, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockhasher_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type mockhasher_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hashedPassword []byte
//   - password string
func (_e *mockhasher_Expecter) Compare(hashedPassword interface{}, password interface{}) *mockhasher_Compare_Call {
	return &mockhasher_Compare_Call{Call: _e.mock.On("Compare", hashedPassword, password)}
}

func (_c *mockhasher_Compare_Call) Run(run func(hashedPassword []byte, password string)) *mockhasher_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockhasher_Compare_Call) Return(err error) *mockhasher_Compare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockhasher_Compare_Call) RunAndReturn(run func(hashedPassword []byte, password string) error) *mockhasher_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type mockhasher
func (_mock *mockhasher) Hash(password string) ([]byte, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockhasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type mockhasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *mockhasher_Expecter) Hash(password interface{}) *mockhasher_Hash_Call {
	return &mockhasher_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *mockhasher_Hash_Call) Run(run func(password string)) *mockhasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockhasher_Hash_Call) Return(bytes []byte, err error) *mockhasher_Hash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *mockhasher_Hash_Call) RunAndReturn(run func(password string) ([]byte, error)) *mockhasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// newMockdispatcher creates a new instance of mockdispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdispatcher {
	mock := &mockdispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdispatcher is an autogenerated mock type for the dispatcher type
type mockdispatcher struct {
	mock.Mock
}

type mockdispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdispatcher) EXPECT() *mockdispatcher_Expecter {
	return &mockdispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type mockdispatcher
func (_mock *mockdispatcher) Dispatch(ctx context.Context, ev event.DomainEvent) error {
	ret := _mock.Called(ctx, ev)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, event.DomainEvent) error); ok {
		r0 = returnFunc(ctx, ev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type mockdispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - ev event.DomainEvent
func (_e *mockdispatcher_Expecter) Dispatch(ctx interface{}, ev interface{}) *mockdispatcher_Dispatch_Call {
	return &mockdispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, ev)}
}

func (_c *mockdispatcher_Dispatch_Call) Run(run func(ctx context.Context, ev event.DomainEvent)) *mockdispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 event.DomainEvent
		if args[1] != nil {
			arg1 = args[1].(event.DomainEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdispatcher_Dispatch_Call) Return(err error) *mockdispatcher_Dispatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdispatcher_Dispatch_Call) RunAndReturn(run func(ctx context.Context, ev event.DomainEvent) error) *mockdispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}
