// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user_test

import (
	"context"
	"time"

	"github.com/Housiadas/cerberus/internal/types/event"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// newMockgenerator creates a new instance of mockgenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockgenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockgenerator {
	mock := &mockgenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockgenerator is an autogenerated mock type for the generator type
type mockgenerator struct {
	mock.Mock
}

type mockgenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockgenerator) EXPECT() *mockgenerator_Expecter {
	return &mockgenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type mockgenerator
func (_mock *mockgenerator) Generate() (uuid.UUID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uuid.UUID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockgenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type mockgenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *mockgenerator_Expecter) Generate() *mockgenerator_Generate_Call {
	return &mockgenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *mockgenerator_Generate_Call) Run(run func()) *mockgenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockgenerator_Generate_Call) Return(uUID uuid.UUID, err error) *mockgenerator_Generate_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *mockgenerator_Generate_Call) RunAndReturn(run func() (uuid.UUID, error)) *mockgenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockclock creates a new instance of mockclock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockclock(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockclock {
	mock := &mockclock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockclock is an autogenerated mock type for the clock type
type mockclock struct {
	mock.Mock
}

type mockclock_Expecter struct {
	mock *mock.Mock
}

func (_m *mockclock) EXPECT() *mockclock_Expecter {
	return &mockclock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type mockclock
func (_mock *mockclock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// mockclock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type mockclock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *mockclock_Expecter) Now() *mockclock_Now_Call {
	return &mockclock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *mockclock_Now_Call) Run(run func()) *mockclock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockclock_Now_Call) Return(time1 time.Time) *mockclock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *mockclock_Now_Call) RunAndReturn(run func() time.Time) *mockclock_Now_Call {
	_c.Call.Return(run)
	return _c
}

// newMockhasher creates a new instance of mockhasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockhasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockhasher {
	mock := &mockhasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockhasher is an autogenerated mock type for the hasher type
type mockhasher struct {
	mock.Mock
}

type mockhasher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockhasher) EXPECT() *mockhasher_Expecter {
	return &mockhasher_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type mockhasher
func (_mock *mockhasher) Compare(hashedPassword []byte, password string) error {
	ret := _mock.Called(hashedPassword, password)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, string) error); ok {
		r0 = returnFunc(hashedPassword, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockhasher_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type mockhasher_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hashedPassword []byte
//   - password string
func (_e *mockhasher_Expecter) Compare(hashedPassword interface{}, password interface{}) *mockhasher_Compare_Call {
	return &mockhasher_Compare_Call{Call: _e.mock.On("Compare", hashedPassword, password)}
}

func (_c *mockhasher_Compare_Call) Run(run func(hashedPassword []byte, password string)) *mockhasher_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockhasher_Compare_Call) Return(err error) *mockhasher_Compare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockhasher_Compare_Call) RunAndReturn(run func(hashedPassword []byte, password string) error) *mockhasher_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type mockhasher
func (_mock *mockhasher) Hash(password string) ([]byte, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockhasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type mockhasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *mockhasher_Expecter) Hash(password interface{}) *mockhasher_Hash_Call {
	return &mockhasher_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *mockhasher_Hash_Call) Run(run func(password string)) *mockhasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockhasher_Hash_Call) Return(bytes []byte, err error) *mockhasher_Hash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *mockhasher_Hash_Call) RunAndReturn(run func(password string) ([]byte, error)) *mockhasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// newMockdispatcher creates a new instance of mockdispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdispatcher {
	mock := &mockdispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdispatcher is an autogenerated mock type for the dispatcher type
type mockdispatcher struct {
	mock.Mock
}

type mockdispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdispatcher) EXPECT() *mockdispatcher_Expecter {
	return &mockdispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type mockdispatcher
func (_mock *mockdispatcher) Dispatch(ctx context.Context, ev event.DomainEvent) error {
	ret := _mock.Called(ctx, ev)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, event.DomainEvent) error); ok {
		r0 = returnFunc(ctx, ev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type mockdispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - ev event.DomainEvent
func (_e *mockdispatcher_Expecter) Dispatch(ctx interface{}, ev interface{}) *mockdispatcher_Dispatch_Call {
	return &mockdispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, ev)}
}

func (_c *mockdispatcher_Dispatch_Call) Run(run func(ctx context.Context, ev event.DomainEvent)) *mockdispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 event.DomainEvent
		if args[1] != nil {
			arg1 = args[1].(event.DomainEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdispatcher_Dispatch_Call) Return(err error) *mockdispatcher_Dispatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdispatcher_Dispatch_Call) RunAndReturn(run func(ctx context.Context, ev event.DomainEvent) error) *mockdispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}
