// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kafka

import (
	"context"

	"github.com/confluentinc/confluent-kafka-go/v2/kafka"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConsumer creates a new instance of MockConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumer {
	mock := &MockConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConsumer is an autogenerated mock type for the Consumer type
type MockConsumer struct {
	mock.Mock
}

type MockConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumer) EXPECT() *MockConsumer_Expecter {
	return &MockConsumer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockConsumer
func (_mock *MockConsumer) Close() {
	_mock.Called()
	return
}

// MockConsumer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockConsumer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockConsumer_Expecter) Close() *MockConsumer_Close_Call {
	return &MockConsumer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockConsumer_Close_Call) Run(run func()) *MockConsumer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumer_Close_Call) Return() *MockConsumer_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConsumer_Close_Call) RunAndReturn(run func()) *MockConsumer_Close_Call {
	_c.Run(run)
	return _c
}

// Consume provides a mock function for the type MockConsumer
func (_mock *MockConsumer) Consume(ctx context.Context, msg *kafka.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsumer_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockConsumer_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *kafka.Message
func (_e *MockConsumer_Expecter) Consume(ctx interface{}, msg interface{}) *MockConsumer_Consume_Call {
	return &MockConsumer_Consume_Call{Call: _e.mock.On("Consume", ctx, msg)}
}

func (_c *MockConsumer_Consume_Call) Run(run func(ctx context.Context, msg *kafka.Message)) *MockConsumer_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kafka.Message
		if args[1] != nil {
			arg1 = args[1].(*kafka.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConsumer_Consume_Call) Return(err error) *MockConsumer_Consume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsumer_Consume_Call) RunAndReturn(run func(ctx context.Context, msg *kafka.Message) error) *MockConsumer_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockConsumer
func (_mock *MockConsumer) Subscribe(topic string) error {
	ret := _mock.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(topic)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsumer_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockConsumer_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topic string
func (_e *MockConsumer_Expecter) Subscribe(topic interface{}) *MockConsumer_Subscribe_Call {
	return &MockConsumer_Subscribe_Call{Call: _e.mock.On("Subscribe", topic)}
}

func (_c *MockConsumer_Subscribe_Call) Run(run func(topic string)) *MockConsumer_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConsumer_Subscribe_Call) Return(err error) *MockConsumer_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsumer_Subscribe_Call) RunAndReturn(run func(topic string) error) *MockConsumer_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockProducer
func (_mock *MockProducer) Close() {
	_mock.Called()
	return
}

// MockProducer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockProducer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockProducer_Expecter) Close() *MockProducer_Close_Call {
	return &MockProducer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockProducer_Close_Call) Run(run func()) *MockProducer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProducer_Close_Call) Return() *MockProducer_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProducer_Close_Call) RunAndReturn(run func()) *MockProducer_Close_Call {
	_c.Run(run)
	return _c
}

// Flush provides a mock function for the type MockProducer
func (_mock *MockProducer) Flush(timeoutMs int) int {
	ret := _mock.Called(timeoutMs)

	if len(ret) == 0 {
		panic("no return value specified for Flush")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(int) int); ok {
		r0 = returnFunc(timeoutMs)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockProducer_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type MockProducer_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
//   - timeoutMs int
func (_e *MockProducer_Expecter) Flush(timeoutMs interface{}) *MockProducer_Flush_Call {
	return &MockProducer_Flush_Call{Call: _e.mock.On("Flush", timeoutMs)}
}

func (_c *MockProducer_Flush_Call) Run(run func(timeoutMs int)) *MockProducer_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProducer_Flush_Call) Return(n int) *MockProducer_Flush_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockProducer_Flush_Call) RunAndReturn(run func(timeoutMs int) int) *MockProducer_Flush_Call {
	_c.Call.Return(run)
	return _c
}

// Produce provides a mock function for the type MockProducer
func (_mock *MockProducer) Produce(ctx context.Context, msg *kafka.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProducer_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type MockProducer_Produce_Call struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *kafka.Message
func (_e *MockProducer_Expecter) Produce(ctx interface{}, msg interface{}) *MockProducer_Produce_Call {
	return &MockProducer_Produce_Call{Call: _e.mock.On("Produce", ctx, msg)}
}

func (_c *MockProducer_Produce_Call) Run(run func(ctx context.Context, msg *kafka.Message)) *MockProducer_Produce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kafka.Message
		if args[1] != nil {
			arg1 = args[1].(*kafka.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProducer_Produce_Call) Return(err error) *MockProducer_Produce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProducer_Produce_Call) RunAndReturn(run func(ctx context.Context, msg *kafka.Message) error) *MockProducer_Produce_Call {
	_c.Call.Return(run)
	return _c
}
