apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vault.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: vault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["vault", "server", "-dev", "-dev-root-token-id={{ .Values.devToken }}", "-dev-listen-address=0.0.0.0:8200"]
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
              name: http
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "{{ .Values.devToken }}"
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/sys/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: init-script
              mountPath: /vault/scripts
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 5 && /bin/sh /vault/scripts/init.sh"]
      volumes:
        - name: init-script
          configMap:
            name: {{ include "vault.fullname" . }}-init
            defaultMode: 0755
