// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package refresh_token

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockStorer
func (_mock *MockStorer) Create(ctx context.Context, token RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStorer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token RefreshToken
func (_e *MockStorer_Expecter) Create(ctx interface{}, token interface{}) *MockStorer_Create_Call {
	return &MockStorer_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockStorer_Create_Call) Run(run func(ctx context.Context, token RefreshToken)) *MockStorer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 RefreshToken
		if args[1] != nil {
			arg1 = args[1].(RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Create_Call) Return(err error) *MockStorer_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Create_Call) RunAndReturn(run func(ctx context.Context, token RefreshToken) error) *MockStorer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockStorer
func (_mock *MockStorer) Delete(ctx context.Context, token RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - token RefreshToken
func (_e *MockStorer_Expecter) Delete(ctx interface{}, token interface{}) *MockStorer_Delete_Call {
	return &MockStorer_Delete_Call{Call: _e.mock.On("Delete", ctx, token)}
}

func (_c *MockStorer_Delete_Call) Run(run func(ctx context.Context, token RefreshToken)) *MockStorer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 RefreshToken
		if args[1] != nil {
			arg1 = args[1].(RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Delete_Call) Return(err error) *MockStorer_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Delete_Call) RunAndReturn(run func(ctx context.Context, token RefreshToken) error) *MockStorer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// QueryByToken provides a mock function for the type MockStorer
func (_mock *MockStorer) QueryByToken(ctx context.Context, token string) (RefreshToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for QueryByToken")
	}

	var r0 RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (RefreshToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) RefreshToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(RefreshToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_QueryByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryByToken'
type MockStorer_QueryByToken_Call struct {
	*mock.Call
}

// QueryByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockStorer_Expecter) QueryByToken(ctx interface{}, token interface{}) *MockStorer_QueryByToken_Call {
	return &MockStorer_QueryByToken_Call{Call: _e.mock.On("QueryByToken", ctx, token)}
}

func (_c *MockStorer_QueryByToken_Call) Run(run func(ctx context.Context, token string)) *MockStorer_QueryByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_QueryByToken_Call) Return(refreshToken RefreshToken, err error) *MockStorer_QueryByToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockStorer_QueryByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (RefreshToken, error)) *MockStorer_QueryByToken_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockStorer
func (_mock *MockStorer) Revoke(ctx context.Context, token RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockStorer_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - token RefreshToken
func (_e *MockStorer_Expecter) Revoke(ctx interface{}, token interface{}) *MockStorer_Revoke_Call {
	return &MockStorer_Revoke_Call{Call: _e.mock.On("Revoke", ctx, token)}
}

func (_c *MockStorer_Revoke_Call) Run(run func(ctx context.Context, token RefreshToken)) *MockStorer_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 RefreshToken
		if args[1] != nil {
			arg1 = args[1].(RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Revoke_Call) Return(err error) *MockStorer_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Revoke_Call) RunAndReturn(run func(ctx context.Context, token RefreshToken) error) *MockStorer_Revoke_Call {
	_c.Call.Return(run)
	return _c
}
