// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package refresh_token_test

import (
	"context"
	"time"

	"github.com/Housiadas/cerberus/db/sqlc"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// newMockgenerator creates a new instance of mockgenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockgenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockgenerator {
	mock := &mockgenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockgenerator is an autogenerated mock type for the generator type
type mockgenerator struct {
	mock.Mock
}

type mockgenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockgenerator) EXPECT() *mockgenerator_Expecter {
	return &mockgenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type mockgenerator
func (_mock *mockgenerator) Generate() (uuid.UUID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uuid.UUID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockgenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type mockgenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *mockgenerator_Expecter) Generate() *mockgenerator_Generate_Call {
	return &mockgenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *mockgenerator_Generate_Call) Run(run func()) *mockgenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockgenerator_Generate_Call) Return(uUID uuid.UUID, err error) *mockgenerator_Generate_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *mockgenerator_Generate_Call) RunAndReturn(run func() (uuid.UUID, error)) *mockgenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockclock creates a new instance of mockclock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockclock(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockclock {
	mock := &mockclock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockclock is an autogenerated mock type for the clock type
type mockclock struct {
	mock.Mock
}

type mockclock_Expecter struct {
	mock *mock.Mock
}

func (_m *mockclock) EXPECT() *mockclock_Expecter {
	return &mockclock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type mockclock
func (_mock *mockclock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// mockclock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type mockclock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *mockclock_Expecter) Now() *mockclock_Now_Call {
	return &mockclock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *mockclock_Now_Call) Run(run func()) *mockclock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockclock_Now_Call) Return(time1 time.Time) *mockclock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *mockclock_Now_Call) RunAndReturn(run func() time.Time) *mockclock_Now_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstorer creates a new instance of mockstorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstorer {
	mock := &mockstorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstorer is an autogenerated mock type for the storer type
type mockstorer struct {
	mock.Mock
}

type mockstorer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstorer) EXPECT() *mockstorer_Expecter {
	return &mockstorer_Expecter{mock: &_m.Mock}
}

// CreateRefreshToken provides a mock function for the type mockstorer
func (_mock *mockstorer) CreateRefreshToken(ctx context.Context, arg db.CreateRefreshTokenParams) (db.RefreshToken, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 db.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateRefreshTokenParams) (db.RefreshToken, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateRefreshTokenParams) db.RefreshToken); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.RefreshToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateRefreshTokenParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstorer_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type mockstorer_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateRefreshTokenParams
func (_e *mockstorer_Expecter) CreateRefreshToken(ctx interface{}, arg interface{}) *mockstorer_CreateRefreshToken_Call {
	return &mockstorer_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", ctx, arg)}
}

func (_c *mockstorer_CreateRefreshToken_Call) Run(run func(ctx context.Context, arg db.CreateRefreshTokenParams)) *mockstorer_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateRefreshTokenParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateRefreshTokenParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_CreateRefreshToken_Call) Return(refreshToken db.RefreshToken, err error) *mockstorer_CreateRefreshToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *mockstorer_CreateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateRefreshTokenParams) (db.RefreshToken, error)) *mockstorer_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenByToken provides a mock function for the type mockstorer
func (_mock *mockstorer) GetRefreshTokenByToken(ctx context.Context, token string) (db.RefreshToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenByToken")
	}

	var r0 db.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (db.RefreshToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) db.RefreshToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(db.RefreshToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstorer_GetRefreshTokenByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenByToken'
type mockstorer_GetRefreshTokenByToken_Call struct {
	*mock.Call
}

// GetRefreshTokenByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *mockstorer_Expecter) GetRefreshTokenByToken(ctx interface{}, token interface{}) *mockstorer_GetRefreshTokenByToken_Call {
	return &mockstorer_GetRefreshTokenByToken_Call{Call: _e.mock.On("GetRefreshTokenByToken", ctx, token)}
}

func (_c *mockstorer_GetRefreshTokenByToken_Call) Run(run func(ctx context.Context, token string)) *mockstorer_GetRefreshTokenByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_GetRefreshTokenByToken_Call) Return(refreshToken db.RefreshToken, err error) *mockstorer_GetRefreshTokenByToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *mockstorer_GetRefreshTokenByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (db.RefreshToken, error)) *mockstorer_GetRefreshTokenByToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function for the type mockstorer
func (_mock *mockstorer) RevokeRefreshToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstorer_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type mockstorer_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *mockstorer_Expecter) RevokeRefreshToken(ctx interface{}, token interface{}) *mockstorer_RevokeRefreshToken_Call {
	return &mockstorer_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, token)}
}

func (_c *mockstorer_RevokeRefreshToken_Call) Run(run func(ctx context.Context, token string)) *mockstorer_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstorer_RevokeRefreshToken_Call) Return(err error) *mockstorer_RevokeRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstorer_RevokeRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *mockstorer_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
