// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package role_test

import (
	"context"

	"github.com/Housiadas/cerberus/internal/types/event"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// newMockgenerator creates a new instance of mockgenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockgenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockgenerator {
	mock := &mockgenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockgenerator is an autogenerated mock type for the generator type
type mockgenerator struct {
	mock.Mock
}

type mockgenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockgenerator) EXPECT() *mockgenerator_Expecter {
	return &mockgenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type mockgenerator
func (_mock *mockgenerator) Generate() (uuid.UUID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uuid.UUID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockgenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type mockgenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *mockgenerator_Expecter) Generate() *mockgenerator_Generate_Call {
	return &mockgenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *mockgenerator_Generate_Call) Run(run func()) *mockgenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockgenerator_Generate_Call) Return(uUID uuid.UUID, err error) *mockgenerator_Generate_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *mockgenerator_Generate_Call) RunAndReturn(run func() (uuid.UUID, error)) *mockgenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockdispatcher creates a new instance of mockdispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdispatcher {
	mock := &mockdispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdispatcher is an autogenerated mock type for the dispatcher type
type mockdispatcher struct {
	mock.Mock
}

type mockdispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdispatcher) EXPECT() *mockdispatcher_Expecter {
	return &mockdispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type mockdispatcher
func (_mock *mockdispatcher) Dispatch(ctx context.Context, ev event.DomainEvent) error {
	ret := _mock.Called(ctx, ev)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, event.DomainEvent) error); ok {
		r0 = returnFunc(ctx, ev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type mockdispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - ev event.DomainEvent
func (_e *mockdispatcher_Expecter) Dispatch(ctx interface{}, ev interface{}) *mockdispatcher_Dispatch_Call {
	return &mockdispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, ev)}
}

func (_c *mockdispatcher_Dispatch_Call) Run(run func(ctx context.Context, ev event.DomainEvent)) *mockdispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 event.DomainEvent
		if args[1] != nil {
			arg1 = args[1].(event.DomainEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdispatcher_Dispatch_Call) Return(err error) *mockdispatcher_Dispatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdispatcher_Dispatch_Call) RunAndReturn(run func(ctx context.Context, ev event.DomainEvent) error) *mockdispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}
