// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user_roles_permissions

import (
	"context"

	"github.com/Housiadas/cerberus/internal/utils/page"
	"github.com/Housiadas/cerberus/pkg/order"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockStorer
func (_mock *MockStorer) Count(ctx context.Context, filter QueryFilter) (int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, QueryFilter) (int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, QueryFilter) int); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, QueryFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockStorer_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - filter QueryFilter
func (_e *MockStorer_Expecter) Count(ctx interface{}, filter interface{}) *MockStorer_Count_Call {
	return &MockStorer_Count_Call{Call: _e.mock.On("Count", ctx, filter)}
}

func (_c *MockStorer_Count_Call) Run(run func(ctx context.Context, filter QueryFilter)) *MockStorer_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 QueryFilter
		if args[1] != nil {
			arg1 = args[1].(QueryFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_Count_Call) Return(n int, err error) *MockStorer_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStorer_Count_Call) RunAndReturn(run func(ctx context.Context, filter QueryFilter) (int, error)) *MockStorer_Count_Call {
	_c.Call.Return(run)
	return _c
}

// HasPermission provides a mock function for the type MockStorer
func (_mock *MockStorer) HasPermission(ctx context.Context, userID uuid.UUID, permissionName string) (bool, error) {
	ret := _mock.Called(ctx, userID, permissionName)

	if len(ret) == 0 {
		panic("no return value specified for HasPermission")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return returnFunc(ctx, userID, permissionName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = returnFunc(ctx, userID, permissionName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, permissionName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_HasPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPermission'
type MockStorer_HasPermission_Call struct {
	*mock.Call
}

// HasPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - permissionName string
func (_e *MockStorer_Expecter) HasPermission(ctx interface{}, userID interface{}, permissionName interface{}) *MockStorer_HasPermission_Call {
	return &MockStorer_HasPermission_Call{Call: _e.mock.On("HasPermission", ctx, userID, permissionName)}
}

func (_c *MockStorer_HasPermission_Call) Run(run func(ctx context.Context, userID uuid.UUID, permissionName string)) *MockStorer_HasPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorer_HasPermission_Call) Return(b bool, err error) *MockStorer_HasPermission_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStorer_HasPermission_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, permissionName string) (bool, error)) *MockStorer_HasPermission_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockStorer
func (_mock *MockStorer) Query(ctx context.Context, filter QueryFilter, orderBy order.By, page1 page.Page) ([]UserRolesPermissions, error) {
	ret := _mock.Called(ctx, filter, orderBy, page1)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []UserRolesPermissions
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, QueryFilter, order.By, page.Page) ([]UserRolesPermissions, error)); ok {
		return returnFunc(ctx, filter, orderBy, page1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, QueryFilter, order.By, page.Page) []UserRolesPermissions); ok {
		r0 = returnFunc(ctx, filter, orderBy, page1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]UserRolesPermissions)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, QueryFilter, order.By, page.Page) error); ok {
		r1 = returnFunc(ctx, filter, orderBy, page1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockStorer_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - filter QueryFilter
//   - orderBy order.By
//   - page1 page.Page
func (_e *MockStorer_Expecter) Query(ctx interface{}, filter interface{}, orderBy interface{}, page1 interface{}) *MockStorer_Query_Call {
	return &MockStorer_Query_Call{Call: _e.mock.On("Query", ctx, filter, orderBy, page1)}
}

func (_c *MockStorer_Query_Call) Run(run func(ctx context.Context, filter QueryFilter, orderBy order.By, page1 page.Page)) *MockStorer_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 QueryFilter
		if args[1] != nil {
			arg1 = args[1].(QueryFilter)
		}
		var arg2 order.By
		if args[2] != nil {
			arg2 = args[2].(order.By)
		}
		var arg3 page.Page
		if args[3] != nil {
			arg3 = args[3].(page.Page)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorer_Query_Call) Return(userRolesPermissionss []UserRolesPermissions, err error) *MockStorer_Query_Call {
	_c.Call.Return(userRolesPermissionss, err)
	return _c
}

func (_c *MockStorer_Query_Call) RunAndReturn(run func(ctx context.Context, filter QueryFilter, orderBy order.By, page1 page.Page) ([]UserRolesPermissions, error)) *MockStorer_Query_Call {
	_c.Call.Return(run)
	return _c
}
